return {
    Lighting = {
        ClockTime = 17.71666717529297, 
        ColorShift_Bottom = Color3.fromRGB(0, 0, 0), 
        FogColor = Color3.fromRGB(192, 192, 192), 
        FogEnd = 100000, 
        FogStart = 0, 
        EnvironmentDiffuseScale = 1, 
        EnvironmentSpecularScale = 1, 
        ExposureCompensation = -1.25, 
        GeographicLatitude = -100, 
        Ambient = Color3.fromRGB(168, 168, 168), 
        OutdoorAmbient = Color3.fromRGB(33, 96, 99), 
        ShadowSoftness = 0.20000000298023224, 
        Brightness = 1, 
        ColorShift_Top = Color3.fromRGB(163, 71, 91), 
        GlobalShadows = true
    }, 
    Sky = {
        CelestialBodiesShown = true, 
        MoonAngularSize = 11, 
        MoonTextureId = "", 
        SkyboxBk = "rbxassetid://71447178263743", 
        SkyboxDn = "rbxassetid://131053856157800", 
        SkyboxFt = "rbxassetid://71447178263743", 
        SkyboxLf = "rbxassetid://115987501515200", 
        SkyboxRt = "rbxassetid://71447178263743", 
        SkyboxUp = "rbxassetid://133907954941325", 
        StarCount = 3000, 
        SunAngularSize = 0, 
        SunTextureId = "rbxasset://sky/sun.jpg", 
        Name = "SpongebobSky"
    }, 
    Atmosphere = {
        Density = 0.6000000238418579, 
        Offset = 0.25, 
        Name = "Atmosphere", 
        Color = Color3.fromRGB(255, 255, 255), 
        Decay = Color3.fromRGB(191, 74, 179), 
        Glare = 2, 
        Haze = 1.100000023841858
    }, 
    PostEffects = {
        Lighting = {
            BloomEffect = {
                Name = "Bloom", 
                Enabled = true, 
                Intensity = 1, 
                Size = 29, 
                Threshold = 1.843000054359436
            }, 
            ColorCorrectionEffect = {
                Name = "ColorCorrection", 
                Brightness = 0.10000000149011612, 
                Contrast = 0.3499999940395355, 
                Enabled = true, 
                Saturation = 0.20000000298023224, 
                TintColor = Color3.fromRGB(255, 139, 230)
            }, 
            DepthOfFieldEffect = {
                Name = "DepthOfField", 
                Enabled = true, 
                FarIntensity = 0.4320000112056732, 
                FocusDistance = 0, 
                InFocusRadius = 200, 
                NearIntensity = 0.75
            }, 
            SunRaysEffect = {
                Name = "SunRays", 
                Enabled = true, 
                Intensity = 0.10000000149011612, 
                Spread = 1
            }
        }, 
        Camera = {}
    }
};