return {
    {
        badgeName = "Spongebob", 
        badgeId = 4.14949227961851E15
    }, 
    {
        badgeName = "Patrick", 
        badgeId = 3.222872806234834E15
    }, 
    {
        badgeName = "Sandy", 
        badgeId = 4.418208411782293E15
    }, 
    {
        badgeName = "Squidward", 
        badgeId = 3.365303611596355E15
    }, 
    {
        badgeName = "Spongebob_Test", 
        badgeId = 4.1396992248063E15
    }, 
    {
        badgeName = "Patrick_Test", 
        badgeId = 1.536538049874586E15
    }, 
    {
        badgeName = "Sandy_Test", 
        badgeId = 1.26282974205867E15
    }, 
    {
        badgeName = "Squidward_Test", 
        badgeId = 2.104440568684284E15
    }
};