return {
    ShopOrder = 2, 
    Cost = {
        currencyName = "Gems", 
        price = 500
    }, 
    Pool = {
        RaritiesPool = {
            Rare = {
                weight = 54.99, 
                shinyWeight = 2.25, 
                megaWeight = 1.25, 
                megaShinyWeight = 0.5
            }, 
            Epic = {
                weight = 30, 
                shinyWeight = 1, 
                megaWeight = 0.5, 
                megaShinyWeight = 0.25
            }, 
            Legendary = {
                weight = 11.95, 
                shinyWeight = 0.1, 
                megaWeight = 0.075, 
                megaShinyWeight = 0.025
            }, 
            Mythic = {
                weight = 3, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }, 
            Secret = {
                weight = 0.05, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }, 
            Exotic = {
                weight = 0.01, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }
        }, 
        UnitsPool = {
            Rare = {
                {
                    type = "Unit", 
                    name = "GrandmaSquarePants", 
                    weight = 6
                }, 
                {
                    type = "Unit", 
                    name = "OldManJenkins", 
                    weight = 6
                }, 
                {
                    type = "Unit", 
                    name = "Pearl", 
                    weight = 5
                }, 
                {
                    type = "Unit", 
                    name = "KevinCCucumber", 
                    weight = 6.5
                }, 
                {
                    type = "Unit", 
                    name = "MrsPuff", 
                    weight = 8
                }, 
                {
                    type = "Unit", 
                    name = "LordRoyalHighness", 
                    weight = 6.5
                }, 
                {
                    type = "Unit", 
                    name = "KrustyKrab", 
                    weight = 6
                }, 
                {
                    type = "Unit", 
                    name = "ElasticWaistband", 
                    weight = 4.5
                }, 
                {
                    type = "Unit", 
                    name = "KarateSandy", 
                    weight = 6.5
                }
            }, 
            Epic = {
                {
                    type = "Unit", 
                    name = "LarryTheLobster", 
                    weight = 6
                }, 
                {
                    type = "Unit", 
                    name = "Karen", 
                    weight = 6
                }, 
                {
                    type = "Unit", 
                    name = "PrincessMindy", 
                    weight = 6
                }, 
                {
                    type = "Unit", 
                    name = "DirtyBubble", 
                    weight = 5
                }, 
                {
                    type = "Unit", 
                    name = "MermaidManSpongebob", 
                    weight = 4
                }, 
                {
                    type = "Unit", 
                    name = "SandCreature", 
                    weight = 3
                }
            }, 
            Legendary = {
                {
                    type = "Unit", 
                    name = "MrKrabs", 
                    weight = 3
                }, 
                {
                    type = "Unit", 
                    name = "Plankton", 
                    weight = 3
                }, 
                {
                    type = "Unit", 
                    name = "Doodlebob", 
                    weight = 3
                }, 
                {
                    type = "Unit", 
                    name = "MissAppear", 
                    weight = 2
                }, 
                {
                    type = "Unit", 
                    name = "Jojo", 
                    weight = 0.95
                }
            }, 
            Mythic = {
                {
                    type = "Unit", 
                    name = "SmittyWerbenjagermanjensen", 
                    weight = 0.35
                }, 
                {
                    type = "Unit", 
                    name = "RealisticFishHead", 
                    weight = 0.35
                }, 
                {
                    type = "Unit", 
                    name = "KingNeptune", 
                    weight = 0.35
                }, 
                {
                    type = "Unit", 
                    name = "ManRay", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "MermaidMan", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "DirtyDan", 
                    weight = 0.25
                }, 
                {
                    type = "Unit", 
                    name = "PinheadLarry", 
                    weight = 0.25
                }, 
                {
                    type = "Unit", 
                    name = "Tiff", 
                    weight = 0.125
                }, 
                {
                    type = "Unit", 
                    name = "Bert", 
                    weight = 0.125
                }
            }, 
            Secret = {
                {
                    type = "Unit", 
                    name = "CyborgPlankton", 
                    weight = 0.035, 
                    secretUnit = true
                }, 
                {
                    type = "Unit", 
                    name = "SeaBear", 
                    weight = 0.015, 
                    secretUnit = true
                }, 
                {
                    type = "Unit", 
                    name = "Plank-Ton", 
                    weight = 0.004, 
                    secretUnit = true
                }
            }, 
            Exotic = {
                {
                    type = "Unit", 
                    name = "PatTheHapless", 
                    weight = 0.005
                }, 
                {
                    type = "Unit", 
                    name = "CannonballJenkins", 
                    weight = 0.005
                }
            }
        }
    }
};