return {
    ACHIEVEMENT_REWARDS = {
        TIER_1 = {
            Defeat = {
                {
                    type = "Currency", 
                    name = "Coins", 
                    amount = 5000
                }
            }, 
            ["3Star"] = {
                {
                    type = "Currency", 
                    name = "Gems", 
                    amount = 1000
                }
            }
        }, 
        TIER_2 = {
            Defeat = {
                {
                    type = "Currency", 
                    name = "MagicConch", 
                    amount = 10
                }
            }, 
            ["3Star"] = {
                {
                    type = "Inventory", 
                    name = "LegendaryTreasureChest", 
                    amount = 10
                }
            }
        }, 
        TIER_3 = {
            Defeat = {
                {
                    type = "Currency", 
                    name = "GoldenTraitRolls", 
                    amount = 10
                }
            }, 
            ["3Star"] = {
                {
                    type = "Inventory", 
                    name = "MythicTreasureChest", 
                    amount = 5
                }
            }
        }, 
        TIER_4 = {
            Defeat = {
                {
                    type = "Inventory", 
                    name = "SecretTreasureChest", 
                    amount = 1
                }
            }, 
            ["3Star"] = {
                {
                    type = "Inventory", 
                    name = "LionFish", 
                    amount = 1
                }
            }
        }
    }
};