return {
    VariantsPool = {
        Normal = {
            weight = 95
        }, 
        Shiny = {
            weight = 3
        }, 
        Wumbo = {
            weight = 1.5
        }, 
        ShinyWumbo = {
            weight = 0.5
        }
    }, 
    RaritiesPool = {
        Epic = {
            weight = 70.5
        }, 
        Legendary = {
            weight = 27.3
        }, 
        Mythic = {
            weight = 2
        }, 
        Secret = {
            weight = 0.2
        }
    }, 
    LootPool = {
        Epic = {
            {
                type = "Unit", 
                name = "PattyObsessedSquidward", 
                extraData = {}, 
                amount = 1, 
                weight = 45
            }, 
            {
                type = "Unit", 
                name = "GrannyTentacles", 
                extraData = {}, 
                amount = 1, 
                weight = 25.5
            }
        }, 
        Legendary = {
            {
                type = "Unit", 
                name = "SnowMollusk", 
                extraData = {}, 
                amount = 1, 
                weight = 18.4
            }, 
            {
                type = "Unit", 
                name = "Spot", 
                extraData = {}, 
                amount = 1, 
                weight = 8.9
            }
        }, 
        Mythic = {
            {
                type = "Unit", 
                name = "LordPoltergeist", 
                extraData = {}, 
                amount = 1, 
                weight = 2
            }
        }, 
        Secret = {
            {
                type = "Unit", 
                name = "Dennis", 
                extraData = {}, 
                amount = 1, 
                weight = 0.2
            }
        }
    }
};