local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = game:GetService("RunService");
local _ = require(l_ReplicatedStorage_0.Shared.Data.Purchases);
return {
    {
        reward = {
            type = "Inventory", 
            name = "TreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "TreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer1"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "TreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "TreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 2
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer2"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 3
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer3"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer4"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 2
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer5"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 3
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer6"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "SecretTreasureChest", 
            amount = 2
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer7"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "SecretTreasureChest", 
            amount = 3
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer8"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "SecretTreasureChest", 
            amount = 5
        }, 
        isFree = false, 
        purchaseName = "ChestForeverOffer9"
    }
};