return {
    KrustyComboMeal = {
        displayName = "Krusty Combo Meal", 
        aura = 3, 
        image = "rbxassetid://113916312479618", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Damage", 
                amount = 10
            }
        }, 
        nerfs = {
            {
                type = "EnemyStat", 
                name = "Speed", 
                amount = 10
            }
        }
    }, 
    JellyfishJam = {
        displayName = "Jellyfish Jam", 
        aura = 3, 
        image = "rbxassetid://94948342199034", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Cooldown", 
                amount = -10
            }
        }, 
        nerfs = {
            {
                type = "EnemyStat", 
                name = "Health", 
                amount = 10
            }
        }
    }, 
    BarnacleBoosters = {
        displayName = "Barnacle Boosters", 
        aura = 3, 
        image = "rbxassetid://116658942392190", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Range", 
                amount = 10
            }
        }, 
        nerfs = {
            {
                type = "TowerStat", 
                name = "Damage", 
                amount = -5
            }
        }
    }, 
    BubbleBlaster9000 = {
        displayName = "Bubble Blaster 9000", 
        aura = 5, 
        image = "rbxassetid://131679949638402", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Cooldown", 
                amount = -15
            }
        }, 
        nerfs = {
            {
                type = "EnemyStat", 
                name = "Health", 
                amount = 10
            }
        }
    }, 
    SpicyKelpChips = {
        displayName = "Spicy Kelp Chips", 
        aura = 5, 
        image = "rbxassetid://95955936198461", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Damage", 
                amount = 15
            }
        }, 
        nerfs = {
            {
                type = "EnemyStat", 
                name = "Speed", 
                amount = 15
            }
        }
    }, 
    SquidwardsClarinetStand = {
        displayName = "Squidwards Clarinet Stand", 
        aura = 5, 
        image = "rbxassetid://72534076718290", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Range", 
                amount = 20
            }
        }, 
        nerfs = {
            {
                type = "TowerStat", 
                name = "Damage", 
                amount = -10
            }
        }
    }, 
    ElectricJellyLure = {
        displayName = "Electric Jelly Lure", 
        aura = 7, 
        image = "rbxassetid://115862131580638", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Range", 
                amount = 40
            }
        }, 
        nerfs = {
            {
                type = "GoldIncome", 
                amount = -50
            }
        }
    }, 
    KrustyKetchupCannon = {
        displayName = "Krusty Ketchup Cannon", 
        aura = 7, 
        image = "rbxassetid://134928827068829", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Damage", 
                amount = 25
            }
        }, 
        nerfs = {
            {
                type = "EnemyStat", 
                name = "Speed", 
                amount = 25
            }
        }
    }, 
    SandysScienceSyrup = {
        displayName = "Sandy's Science Syrup", 
        aura = 7, 
        image = "rbxassetid://101539950072022", 
        buffs = {
            {
                type = "TowerStat", 
                name = "Cooldown", 
                amount = -25
            }
        }, 
        nerfs = {
            {
                type = "EnemyStat", 
                name = "Health", 
                amount = 25
            }
        }
    }
};