return {
    _sheets = {
        [1] = "rbxassetid://138991025023973"
    }, 
    SuperGoo = {
        index = 1, 
        sheet = 1
    }, 
    AcornAlloy = {
        index = 2, 
        sheet = 1
    }, 
    AncientSponge = {
        index = 3, 
        sheet = 1
    }, 
    CorrodedCircuit = {
        index = 4, 
        sheet = 1
    }, 
    MysteryPatty = {
        index = 5, 
        sheet = 1
    }, 
    SecretSauce = {
        index = 6, 
        sheet = 1
    }, 
    BioJellyCache = {
        index = 7, 
        sheet = 1
    }, 
    EVILCore = {
        index = 8, 
        sheet = 1
    }, 
    BubbleDiskette = {
        index = 9, 
        sheet = 1
    }, 
    BubbleResin = {
        index = 10, 
        sheet = 1
    }, 
    BurntScroll = {
        index = 11, 
        sheet = 1
    }, 
    EchoShards = {
        index = 12, 
        sheet = 1
    }, 
    SpectralBarnacles = {
        index = 13, 
        sheet = 1
    }, 
    FrozenCoral = {
        index = 14, 
        sheet = 1
    }, 
    GoldenPattyBun = {
        index = 15, 
        sheet = 1
    }, 
    MoldySponge = {
        index = 16, 
        sheet = 1
    }, 
    GoofyGooberSyrup = {
        index = 17, 
        sheet = 1
    }, 
    GreasyNapkin = {
        index = 18, 
        sheet = 1
    }, 
    HeroEmblem = {
        index = 19, 
        sheet = 1
    }, 
    JellyTendrils = {
        index = 20, 
        sheet = 1
    }, 
    PattyTokens = {
        index = 21, 
        sheet = 1
    }, 
    ScratchedLicensePlate = {
        index = 22, 
        sheet = 1
    }, 
    SeaCrystal = {
        index = 23, 
        sheet = 1
    }, 
    SpectralRope = {
        index = 24, 
        sheet = 1
    }, 
    SuperheroTape = {
        index = 25, 
        sheet = 1
    }, 
    TidalThread = {
        index = 26, 
        sheet = 1
    }
};