return {
    _order = 1, 
    _displayName = "Fry Forge", 
    FullCompletionRewards = {
        {
            type = "Unit", 
            name = "Nosferatu", 
            extraData = {
                Shiny = true, 
                Wumbo = true, 
                Stars = 5
            }, 
            amount = 1
        }
    }; 
    {
        Name = "LabRat1", 
        DisplayName = "Lab Rat I", 
        Description = "Craft 10 Holographic Meatloaf", 
        Type = "Crafted_HolographicMeatloaf", 
        RequiredValue = 10, 
        Rewards = {
            {
                type = "Inventory", 
                name = "MythicTreasureChest", 
                amount = 50
            }
        }
    }, 
    {
        Name = "LabRat2", 
        DisplayName = "Lab Rat II", 
        Description = "Craft 25 Holographic Meatloaf", 
        Type = "Crafted_HolographicMeatloaf", 
        RequiredValue = 25, 
        Rewards = {
            {
                type = "Inventory", 
                name = "SecretTreasureChest", 
                amount = 1
            }
        }
    }, 
    {
        Name = "LabRat3", 
        DisplayName = "Lab Rat III", 
        Description = "Craft 50 Holographic Meatloaf", 
        Type = "Crafted_HolographicMeatloaf", 
        RequiredValue = 50, 
        Rewards = {
            {
                type = "Inventory", 
                name = "ExoticTreasureChest", 
                amount = 1
            }
        }
    }, 
    {
        Name = "GearHead", 
        DisplayName = "Gear Head", 
        Description = "Craft 1 Bikini Bottom Bus", 
        Type = "Crafted_BikiniBottomBus", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "Gems", 
                amount = 5000
            }
        }
    }, 
    {
        Name = "Squad1", 
        DisplayName = "Squad I", 
        Description = "Craft 1 Breakfast Monster", 
        Type = "Crafted_BreakfastMonster", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "Gems", 
                amount = 10000
            }
        }
    }, 
    {
        Name = "Squad2", 
        DisplayName = "Squad II", 
        Description = "Craft 1 Nosferatu", 
        Type = "Crafted_Nosferatu", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "Gems", 
                amount = 25000
            }
        }
    }, 
    {
        Name = "Booster", 
        DisplayName = "Booster", 
        Description = "Craft 1 Power Patty", 
        Type = "Crafted_PowerPatty", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 500
            }
        }
    }, 
    {
        Name = "Wizard", 
        DisplayName = "Wizard", 
        Description = "Craft 1 Shiny Wumbo Potion", 
        Type = "Crafted_ShinyWumboPotion", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "GoldenTraitRolls", 
                amount = 100
            }
        }
    }, 
    {
        Name = "Market1", 
        DisplayName = "Market Stalker I", 
        Description = "Make 25 Mystery Market Purchases", 
        Type = "MysteryMarketPurchase", 
        RequiredValue = 25, 
        Rewards = {
            {
                type = "Currency", 
                name = "Coins", 
                amount = 10000
            }
        }
    }, 
    {
        Name = "Market2", 
        DisplayName = "Market Stalker II", 
        Description = "Make 50 Mystery Market Purchases", 
        Type = "MysteryMarketPurchase", 
        RequiredValue = 50, 
        Rewards = {
            {
                type = "Currency", 
                name = "Coins", 
                amount = 25000
            }
        }
    }, 
    {
        Name = "Market3", 
        DisplayName = "Market Stalker III", 
        Description = "Make 100 Mystery Market Purchases", 
        Type = "MysteryMarketPurchase", 
        RequiredValue = 100, 
        Rewards = {
            {
                type = "Currency", 
                name = "Coins", 
                amount = 50000
            }
        }
    }
};