return {
    OldManJenkins = {
        animationTime = 1.9166666269302368, 
        sustainedHits = {
            {
                start = 0.8333333134651184, 
                multiplier = 1, 
                stop = 1.9166666269302368
            }
        }
    }, 
    Barb = {
        animationTime = 2.8333332538604736, 
        sustainedHits = {
            {
                start = 0.9583333134651184, 
                multiplier = 1, 
                stop = 2.8333332538604736
            }
        }
    }, 
    BandMrsPuff = {
        animationTime = 3.3333332538604736, 
        sustainedHits = {
            {
                start = 1.4666666984558105, 
                multiplier = 1, 
                stop = 3.3333332538604736
            }
        }
    }, 
    MasterUdon = {
        animationTime = 1.7424999475479126, 
        sustainedHits = {
            {
                start = 0.9775000214576721, 
                multiplier = 1, 
                stop = 1.7424999475479126
            }
        }
    }, 
    Plankton = {
        animationTime = 1.2333333492279053, 
        sustainedHits = {
            {
                start = 0.5833333134651184, 
                multiplier = 1, 
                stop = 1.2333333492279053
            }
        }
    }, 
    LarryTheLobster = {
        animationTime = 6, 
        sustainedHits = {
            {
                start = 1.850000023841858, 
                multiplier = 1, 
                stop = 6
            }
        }
    }, 
    HibernationSandy = {
        animationTime = 3.2833333015441895, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.2333333492279053
            }
        }, 
        sustainedHits = {
            {
                start = 2.2333333492279053, 
                multiplier = 1, 
                stop = 3.2833333015441895
            }
        }
    }, 
    Jellien = {
        animationTime = 2.3333332538604736, 
        sustainedHits = {
            {
                start = 0.5833333134651184, 
                multiplier = 1, 
                stop = 2.3333332538604736
            }
        }
    }, 
    Spot = {
        animationTime = 3.566666603088379, 
        sustainedHits = {
            {
                start = 2.566666603088379, 
                multiplier = 1, 
                stop = 3.566666603088379
            }
        }
    }, 
    BunkerBoys = {
        animationTime = 4, 
        singleHits = {
            {
                multiplier = 2, 
                time = 1.6666666269302368
            }, 
            {
                multiplier = 2, 
                time = 2.7666666507720947
            }, 
            {
                multiplier = 2, 
                time = 3.8499999046325684
            }
        }, 
        sustainedHits = {
            {
                start = 0.949999988079071, 
                multiplier = 1, 
                stop = 4
            }
        }
    }, 
    FirstMatePatrick = {
        animationTime = 3, 
        sustainedHits = {
            {
                start = 1.5416666269302368, 
                multiplier = 1, 
                stop = 3
            }
        }
    }, 
    TangoKaren = {
        animationTime = 2.7166666984558105, 
        sustainedHits = {
            {
                start = 0.8666666746139526, 
                multiplier = 1, 
                stop = 2.7166666984558105
            }
        }
    }, 
    KelpyG = {
        animationTime = 4.949999809265137, 
        sustainedHits = {
            {
                start = 0.550000011920929, 
                multiplier = 1, 
                stop = 4.949999809265137
            }
        }
    }, 
    MrMailman = {
        animationTime = 1.4333332777023315, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.4333332777023315
            }
        }
    }, 
    TheTickler = {
        animationTime = 2.4166667461395264, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.4333332777023315
            }
        }, 
        sustainedHits = {
            {
                start = 1.4333332777023315, 
                multiplier = 1, 
                stop = 2.4166667461395264
            }
        }
    }, 
    TheRodent = {
        animationTime = 2.125, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.375
            }, 
            {
                multiplier = 1, 
                time = 0.7083333134651184
            }, 
            {
                multiplier = 1, 
                time = 1.0416666269302368
            }, 
            {
                multiplier = 1, 
                time = 1.3333333730697632
            }, 
            {
                multiplier = 1, 
                time = 1.625
            }, 
            {
                multiplier = 1, 
                time = 1.7916666269302368
            }, 
            {
                multiplier = 1, 
                time = 1.9583333730697632
            }, 
            {
                multiplier = 1, 
                time = 2.125
            }
        }
    }, 
    FilthyPhil = {
        animationTime = 3.4166667461395264, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.375
            }
        }, 
        sustainedHits = {
            {
                start = 1.375, 
                multiplier = 1, 
                stop = 3.4166667461395264
            }
        }
    }, 
    CannonballJenkins = {
        animationTime = 1.2000000476837158, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.2000000476837158
            }
        }
    }, 
    SirPinchAlot = {
        animationTime = 2.299999952316284, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.6333333253860474
            }, 
            {
                multiplier = 1, 
                time = 1.1333333253860474
            }, 
            {
                multiplier = 1, 
                time = 1.7000000476837158
            }, 
            {
                multiplier = 1, 
                time = 2.299999952316284
            }
        }
    }, 
    SquidwardSanta = {
        animationTime = 5, 
        sustainedHits = {
            {
                start = 1.6666666269302368, 
                multiplier = 1, 
                stop = 5
            }
        }
    }, 
    KarateSpongebob = {
        animationTime = 1, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1
            }
        }
    }, 
    Tattletale = {
        animationTime = 3.200000047683716, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.5833333730697632
            }
        }, 
        sustainedHits = {
            {
                start = 1.5833333730697632, 
                multiplier = 1, 
                stop = 3.200000047683716
            }
        }
    }, 
    RedbeardKrabs = {
        animationTime = 4.5, 
        sustainedHits = {
            {
                start = 0.8833333253860474, 
                multiplier = 1, 
                stop = 4.5
            }
        }
    }, 
    GloveWorldSpongebob = {
        animationTime = 3.383333444595337, 
        singleHits = {
            {
                multiplier = 1, 
                time = 3.383333444595337
            }
        }
    }, 
    PrincessMindy = {
        animationTime = 1.5666667222976685, 
        sustainedHits = {
            {
                start = 0.8833333253860474, 
                multiplier = 1, 
                stop = 1.5666667222976685
            }
        }
    }, 
    KrustyKrushers = {
        animationTime = 3.2083332538604736, 
        sustainedHits = {
            {
                start = 1.25, 
                multiplier = 1, 
                stop = 3.2083332538604736
            }
        }
    }, 
    SquilliamFancyson = {
        animationTime = 1.3833333253860474, 
        sustainedHits = {
            {
                start = 0.6333333253860474, 
                multiplier = 1, 
                stop = 1.3833333253860474
            }
        }
    }, 
    Karen2 = {
        animationTime = 2.7833333015441895, 
        sustainedHits = {
            {
                start = 1.3333333730697632, 
                multiplier = 1, 
                stop = 2.7833333015441895
            }
        }
    }, 
    JellienLeader = {
        animationTime = 1.7999999523162842, 
        sustainedHits = {
            {
                start = 1.0833333730697632, 
                multiplier = 1, 
                stop = 1.7999999523162842
            }
        }
    }, 
    KampPatrick = {
        animationTime = 3.333750009536743, 
        sustainedHits = {
            {
                start = 2, 
                multiplier = 1, 
                stop = 3.333750009536743
            }
        }
    }, 
    Doodlebob = {
        animationTime = 1.75, 
        sustainedHits = {
            {
                start = 1.1333333253860474, 
                multiplier = 1, 
                stop = 1.75
            }
        }
    }, 
    JumboShrimp = {
        animationTime = 0.9854166507720947, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.9854166507720947
            }
        }
    }, 
    PatrickSandRobot = {
        animationTime = 1.3166667222976685, 
        sustainedHits = {
            {
                start = 0.5333333611488342, 
                multiplier = 1, 
                stop = 1.3166667222976685
            }
        }
    }, 
    MermaidManSpongebob = {
        animationTime = 3, 
        sustainedHits = {
            {
                start = 0.9666666388511658, 
                multiplier = 1, 
                stop = 3
            }
        }
    }, 
    PoliceFish = {
        animationTime = 3.866666555404663, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.5
            }, 
            {
                multiplier = 1, 
                time = 1.5833333730697632
            }, 
            {
                multiplier = 1, 
                time = 2.183333396911621
            }, 
            {
                multiplier = 1, 
                time = 2.7333333492279053
            }, 
            {
                multiplier = 1, 
                time = 3.366666555404663
            }
        }, 
        sustainedHits = {
            {
                start = 0.3333333432674408, 
                multiplier = 1, 
                stop = 3.866666555404663
            }
        }
    }, 
    CraigMammalton = {
        animationTime = 2.0833332538604736, 
        sustainedHits = {
            {
                start = 0.9166666865348816, 
                multiplier = 1, 
                stop = 2.0833332538604736
            }
        }
    }, 
    PioneerPatrick = {
        animationTime = 1.1833332777023315, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.1833332777023315
            }
        }
    }, 
    Karen = {
        animationTime = 2.7166666984558105, 
        sustainedHits = {
            {
                start = 0.8666666746139526, 
                multiplier = 1, 
                stop = 2.7166666984558105
            }
        }
    }, 
    KingJellyfish = {
        animationTime = 2.5, 
        sustainedHits = {
            {
                start = 1.899999976158142, 
                multiplier = 1, 
                stop = 2.4000000953674316
            }
        }
    }, 
    Mayor = {
        animationTime = 3.5, 
        sustainedHits = {
            {
                start = 0.5, 
                multiplier = 1, 
                stop = 3.5
            }
        }
    }, 
    AlaskanBullWorm = {
        animationTime = 4.316666603088379, 
        singleHits = {
            {
                multiplier = 3, 
                time = 4.316666603088379
            }
        }, 
        sustainedHits = {
            {
                start = 2, 
                multiplier = 1, 
                stop = 3.9000000953674316
            }
        }
    }, 
    MaidSpongebob = {
        animationTime = 3.625, 
        sustainedHits = {
            {
                start = 2, 
                multiplier = 1, 
                stop = 3.625
            }
        }
    }, 
    LippCervas = {
        animationTime = 2.200000047683716, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.5666667222976685
            }
        }, 
        sustainedHits = {
            {
                start = 1.5666667222976685, 
                multiplier = 1, 
                stop = 2.200000047683716
            }
        }
    }, 
    YouToozFred = {
        animationTime = 3.8333332538604736, 
        sustainedHits = {
            {
                start = 1.899999976158142, 
                multiplier = 1, 
                stop = 3.8333332538604736
            }
        }
    }, 
    BreakfastMonster = {
        animationTime = 3.0833332538604736, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.25
            }
        }, 
        sustainedHits = {
            {
                start = 1.25, 
                multiplier = 1, 
                stop = 3.0833332538604736
            }
        }
    }, 
    PerchPerkins = {
        animationTime = 2.3333332538604736, 
        sustainedHits = {
            {
                start = 0.800000011920929, 
                multiplier = 1, 
                stop = 2.3333332538604736
            }
        }
    }, 
    BubbleBass = {
        animationTime = 2.0333333015441895, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.0333333015441895
            }
        }
    }, 
    Planktonamor = {
        animationTime = 1.8333333730697632, 
        sustainedHits = {
            {
                start = 0.6666666865348816, 
                multiplier = 1, 
                stop = 1.8333333730697632
            }
        }
    }, 
    PattyObsessedSquidward = {
        animationTime = 2.2916667461395264, 
        sustainedHits = {
            {
                start = 1.5833333730697632, 
                multiplier = 1, 
                stop = 2.2916667461395264
            }
        }
    }, 
    BikiniBottomPD = {
        animationTime = 1.1833332777023315, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.1833332777023315
            }
        }
    }, 
    ["Plank-Ton"] = {
        animationTime = 2.6666667461395264, 
        sustainedHits = {
            {
                start = 2, 
                multiplier = 1, 
                stop = 2.6666667461395264
            }
        }
    }, 
    ElasticWaistband = {
        animationTime = 2.5, 
        sustainedHits = {
            {
                start = 0.3499999940395355, 
                multiplier = 1, 
                stop = 2.5
            }
        }
    }, 
    BandPearl = {
        animationTime = 5.666666507720947, 
        sustainedHits = {
            {
                start = 3.4666666984558105, 
                multiplier = 1, 
                stop = 5.666666507720947
            }
        }
    }, 
    SandCreature = {
        animationTime = 2.116666555404663, 
        sustainedHits = {
            {
                start = 1.6166666746139526, 
                multiplier = 1, 
                stop = 2.116666555404663
            }
        }
    }, 
    SlappyLaszlo = {
        animationTime = 2.6666667461395264, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.6666667461395264
            }
        }
    }, 
    KevinCCucumber = {
        animationTime = 2.5166666507720947, 
        sustainedHits = {
            {
                start = 0.6000000238418579, 
                multiplier = 1, 
                stop = 2.5166666507720947
            }
        }
    }, 
    Bus = {
        animationTime = 0.25, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.25
            }
        }
    }, 
    TheMoth = {
        animationTime = 3.5833332538604736, 
        sustainedHits = {
            {
                start = 1.0166666507720947, 
                multiplier = 1, 
                stop = 3.5833332538604736
            }
        }
    }, 
    Cyclops = {
        animationTime = 1.149999976158142, 
        sustainedHits = {
            {
                start = 0.6833333373069763, 
                multiplier = 1, 
                stop = 1.149999976158142
            }
        }
    }, 
    MerryGary = {
        animationTime = 1.2666666507720947, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.2666666507720947
            }
        }
    }, 
    DuelSpongebob = {
        animationTime = 2.4000000953674316, 
        sustainedHits = {
            {
                start = 1.2333333492279053, 
                multiplier = 1, 
                stop = 2.4000000953674316
            }
        }
    }, 
    RealisticFishHead = {
        animationTime = 2.7666666507720947, 
        sustainedHits = {
            {
                start = 1.0333333015441895, 
                multiplier = 1, 
                stop = 2.7666666507720947
            }
        }
    }, 
    Fishstick = {
        animationTime = 3.549999952316284, 
        sustainedHits = {
            {
                start = 1.75, 
                multiplier = 1, 
                stop = 3.549999952316284
            }
        }
    }, 
    OldManWalker = {
        animationTime = 4, 
        sustainedHits = {
            {
                start = 0.9166666865348816, 
                multiplier = 1, 
                stop = 4
            }
        }
    }, 
    HelenTheFelon = {
        animationTime = 2.4166667461395264, 
        sustainedHits = {
            {
                start = 0.5975000262260437, 
                multiplier = 1, 
                stop = 2.4166667461395264
            }
        }
    }, 
    FishnetPatrick = {
        animationTime = 2.9000000953674316, 
        sustainedHits = {
            {
                start = 0.5166666507720947, 
                multiplier = 1, 
                stop = 2.9000000953674316
            }
        }
    }, 
    SnowMollusk = {
        animationTime = 6, 
        sustainedHits = {
            {
                start = 1.399999976158142, 
                multiplier = 1, 
                stop = 6
            }
        }
    }, 
    Patricia = {
        animationTime = 2.25, 
        sustainedHits = {
            {
                start = 0.6666666865348816, 
                multiplier = 1, 
                stop = 2.25
            }
        }
    }, 
    KampMrKrabs = {
        animationTime = 1.912500023841858, 
        sustainedHits = {
            {
                start = 1.2324999570846558, 
                multiplier = 1, 
                stop = 1.912500023841858
            }
        }
    }, 
    BuffPatrick = {
        animationTime = 1.5333333015441895, 
        sustainedHits = {
            {
                start = 0.46666666865348816, 
                multiplier = 1, 
                stop = 1.5333333015441895
            }
        }
    }, 
    SquidwardTheSadClown = {
        animationTime = 2.933333396911621, 
        sustainedHits = {
            {
                start = 1.7999999523162842, 
                multiplier = 1, 
                stop = 2.933333396911621
            }
        }
    }, 
    MissAppear = {
        animationTime = 3.1666667461395264, 
        sustainedHits = {
            {
                start = 1.3333333730697632, 
                multiplier = 1, 
                stop = 3.1666667461395264
            }
        }
    }, 
    BubblePoppinThug1 = {
        animationTime = 0.949999988079071, 
        sustainedHits = {
            {
                start = 0.38333332538604736, 
                multiplier = 1, 
                stop = 0.949999988079071
            }
        }
    }, 
    DirtyBubble = {
        animationTime = 0.3499999940395355, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.3499999940395355
            }
        }
    }, 
    Rrarrg = {
        animationTime = 3, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.8500000238418579
            }
        }, 
        sustainedHits = {
            {
                start = 0.8500000238418579, 
                multiplier = 1, 
                stop = 3
            }
        }
    }, 
    Jellyfish = {
        animationTime = 0.7166666388511658, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.7166666388511658
            }
        }
    }, 
    BandMrKrabs = {
        animationTime = 2.433333396911621, 
        sustainedHits = {
            {
                start = 1.2666666507720947, 
                multiplier = 1, 
                stop = 2.433333396911621
            }
        }
    }, 
    SirPatrick = {
        animationTime = 2.4000000953674316, 
        sustainedHits = {
            {
                start = 1.3220833539962769, 
                multiplier = 1, 
                stop = 2.4000000953674316
            }
        }
    }, 
    JackKahunaLaguna = {
        animationTime = 4, 
        sustainedHits = {
            {
                start = 1.625, 
                multiplier = 1, 
                stop = 4
            }
        }
    }, 
    KampMrsPuff = {
        animationTime = 2.2666666507720947, 
        sustainedHits = {
            {
                start = 0.6333333253860474, 
                multiplier = 1, 
                stop = 2.2666666507720947
            }
        }
    }, 
    RippedPantsBob = {
        animationTime = 3.75, 
        sustainedHits = {
            {
                start = 2.183333396911621, 
                multiplier = 1, 
                stop = 3.75
            }
        }
    }, 
    Nosferatu = {
        animationTime = 3.633333444595337, 
        sustainedHits = {
            {
                start = 2.066666603088379, 
                multiplier = 1, 
                stop = 3.633333444595337
            }
        }
    }, 
    BemmyBuddy = {
        animationTime = 1.8333333730697632, 
        sustainedHits = {
            {
                start = 0.9833333492279053, 
                multiplier = 1, 
                stop = 1.8333333730697632
            }
        }
    }, 
    Patar = {
        animationTime = 1.3333333730697632, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.3333333730697632
            }
        }
    }, 
    SquidlyTentacles = {
        animationTime = 3, 
        sustainedHits = {
            {
                start = 0.8999999761581421, 
                multiplier = 1, 
                stop = 3
            }
        }
    }, 
    GoofyGoober = {
        animationTime = 2.8333332538604736, 
        sustainedHits = {
            {
                start = 1.5416666269302368, 
                multiplier = 1, 
                stop = 2.8333332538604736
            }
        }
    }, 
    Squog = {
        animationTime = 0.6666666865348816, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.6666666865348816
            }
        }
    }, 
    SquidasaurusRex = {
        animationTime = 1.4666666984558105, 
        singleHits = {
            {
                multiplier = 2, 
                time = 0.5166666507720947
            }
        }, 
        sustainedHits = {
            {
                start = 0.5166666507720947, 
                multiplier = 1, 
                stop = 1.4666666984558105
            }
        }
    }, 
    PinheadLarry = {
        animationTime = 3.5, 
        sustainedHits = {
            {
                start = 1.75, 
                multiplier = 1, 
                stop = 3.5
            }
        }
    }, 
    KingNeptune = {
        animationTime = 1.4166666269302368, 
        sustainedHits = {
            {
                start = 0.6333333253860474, 
                multiplier = 1, 
                stop = 1.4166666269302368
            }
        }
    }, 
    DirtyDan = {
        animationTime = 0.38333332538604736, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.38333332538604736
            }
        }
    }, 
    GorillaMan = {
        animationTime = 6, 
        sustainedHits = {
            {
                start = 1.9166666269302368, 
                multiplier = 1, 
                stop = 6
            }
        }
    }, 
    MusclebobBuffpants = {
        animationTime = 1.4500000476837158, 
        sustainedHits = {
            {
                start = 0.6833333373069763, 
                multiplier = 1, 
                stop = 1.4500000476837158
            }
        }
    }, 
    DarkKnight = {
        animationTime = 3.0333333015441895, 
        sustainedHits = {
            {
                start = 0.9166666865348816, 
                multiplier = 1, 
                stop = 3.0333333015441895
            }
        }
    }, 
    Gary = {
        animationTime = 3.1666667461395264, 
        sustainedHits = {
            {
                start = 1.4333332777023315, 
                multiplier = 1, 
                stop = 3.1666667461395264
            }
        }
    }, 
    GladiatorPatrick = {
        animationTime = 3.5333333015441895, 
        sustainedHits = {
            {
                start = 2.7166666984558105, 
                multiplier = 1, 
                stop = 3.5333333015441895
            }
        }
    }, 
    MrKrabs = {
        animationTime = 2.75, 
        sustainedHits = {
            {
                start = 0.8999999761581421, 
                multiplier = 1, 
                stop = 2.75
            }
        }
    }, 
    LionFish = {
        animationTime = 2.0999999046325684, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.6000000238418579
            }, 
            {
                multiplier = 1, 
                time = 1.4333332777023315
            }, 
            {
                multiplier = 1, 
                time = 2.0999999046325684
            }
        }
    }, 
    SecretAgentStar = {
        animationTime = 1.7999999523162842, 
        sustainedHits = {
            {
                start = 0.7333333492279053, 
                multiplier = 1, 
                stop = 1.7999999523162842
            }
        }
    }, 
    LordRoyalHighness = {
        animationTime = 2.133333444595337, 
        sustainedHits = {
            {
                start = 0.800000011920929, 
                multiplier = 1, 
                stop = 2.133333444595337
            }
        }
    }, 
    SirSpongebob = {
        animationTime = 2.200000047683716, 
        sustainedHits = {
            {
                start = 0.800000011920929, 
                multiplier = 1, 
                stop = 2.200000047683716
            }
        }
    }, 
    BarnacleMan = {
        animationTime = 7, 
        sustainedHits = {
            {
                start = 0.6666666865348816, 
                multiplier = 1, 
                stop = 7
            }
        }
    }, 
    John = {
        animationTime = 5.333333492279053, 
        sustainedHits = {
            {
                start = 2.799999952316284, 
                multiplier = 1, 
                stop = 5.333333492279053
            }
        }
    }, 
    CaptainZach = {
        animationTime = 3.566666603088379, 
        sustainedHits = {
            {
                start = 0.5666666626930237, 
                multiplier = 1, 
                stop = 2.866666555404663
            }
        }
    }, 
    MermaidMan = {
        animationTime = 3.0333333015441895, 
        sustainedHits = {
            {
                start = 0.4000000059604645, 
                multiplier = 1, 
                stop = 3.0333333015441895
            }
        }
    }, 
    MorbidSpongebob = {
        animationTime = 3.625, 
        sustainedHits = {
            {
                start = 1.2308332920074463, 
                multiplier = 1, 
                stop = 3.625
            }
        }
    }, 
    Spongebob = {
        animationTime = 4.349999904632568, 
        sustainedHits = {
            {
                start = 0.9666666388511658, 
                multiplier = 1, 
                stop = 4.349999904632568
            }
        }
    }, 
    PrincessPearl = {
        animationTime = 1.7666666507720947, 
        sustainedHits = {
            {
                start = 0.7666666507720947, 
                multiplier = 1, 
                stop = 1.7666666507720947
            }
        }
    }, 
    Nat = {
        animationTime = 0.949999988079071, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.949999988079071
            }
        }
    }, 
    Maximus = {
        animationTime = 2.200000047683716, 
        sustainedHits = {
            {
                start = 0.800000011920929, 
                multiplier = 1, 
                stop = 2.200000047683716
            }
        }
    }, 
    BandPlankton = {
        animationTime = 3.25, 
        sustainedHits = {
            {
                start = 2.25, 
                multiplier = 1, 
                stop = 3.25
            }
        }
    }, 
    Bert = {
        animationTime = 2.9833333492279053, 
        sustainedHits = {
            {
                start = 1.2333333492279053, 
                multiplier = 1, 
                stop = 2.9833333492279053
            }
        }
    }, 
    DungeonMaster = {
        animationTime = 5, 
        sustainedHits = {
            {
                start = 1.350000023841858, 
                multiplier = 1, 
                stop = 5
            }
        }
    }, 
    Gene = {
        animationTime = 1.1166666746139526, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.1166666746139526
            }
        }, 
        sustainedHits = {
            {
                start = 0.4333333373069763, 
                multiplier = 1, 
                stop = 1.0166666507720947
            }
        }
    }, 
    Jojo = {
        animationTime = 4.5333333015441895, 
        sustainedHits = {
            {
                start = 1.5666667222976685, 
                multiplier = 1, 
                stop = 4.5333333015441895
            }
        }
    }, 
    OlympianSpongebob = {
        animationTime = 1.9166666269302368, 
        sustainedHits = {
            {
                start = 1.25, 
                multiplier = 1, 
                stop = 1.9166666269302368
            }
        }
    }, 
    Anchovy = {
        animationTime = 4, 
        sustainedHits = {
            {
                start = 1.4166666269302368, 
                multiplier = 1, 
                stop = 4
            }
        }
    }, 
    BubblePoppinThug3 = {
        animationTime = 1, 
        sustainedHits = {
            {
                start = 0.4166666567325592, 
                multiplier = 1, 
                stop = 1
            }
        }
    }, 
    RobotMantis = {
        animationTime = 2.0999999046325684, 
        singleHits = {
            {
                multiplier = 3, 
                time = 1
            }, 
            {
                multiplier = 1, 
                time = 1.25
            }, 
            {
                multiplier = 1, 
                time = 1.2833333015441895
            }, 
            {
                multiplier = 1, 
                time = 1.4666666984558105
            }, 
            {
                multiplier = 1, 
                time = 1.5333333015441895
            }, 
            {
                multiplier = 1, 
                time = 1.7000000476837158
            }, 
            {
                multiplier = 1, 
                time = 1.8166667222976685
            }, 
            {
                multiplier = 1, 
                time = 1.850000023841858
            }, 
            {
                multiplier = 1, 
                time = 2.0333333015441895
            }, 
            {
                multiplier = 1, 
                time = 2.0999999046325684
            }
        }
    }, 
    FabulousSquidward = {
        animationTime = 3.5416667461395264, 
        sustainedHits = {
            {
                start = 2.133333444595337, 
                multiplier = 1, 
                stop = 3.5416667461395264
            }
        }
    }, 
    LloydAndFloyd = {
        animationTime = 1.7833333015441895, 
        sustainedHits = {
            {
                start = 0.6666666865348816, 
                multiplier = 1, 
                stop = 1.7833333015441895
            }
        }
    }, 
    CuddleEHugs = {
        animationTime = 4.666666507720947, 
        sustainedHits = {
            {
                start = 1.2333333492279053, 
                multiplier = 1, 
                stop = 4.666666507720947
            }
        }
    }, 
    KingOfKarateFighters = {
        animationTime = 2.8333332538604736, 
        sustainedHits = {
            {
                start = 0.5833333134651184, 
                multiplier = 1, 
                stop = 2.8333332538604736
            }
        }
    }, 
    IceSpice = {
        animationTime = 4.625, 
        sustainedHits = {
            {
                start = 1.75, 
                multiplier = 1, 
                stop = 4.625
            }
        }
    }, 
    PrehistoricGary = {
        animationTime = 5, 
        sustainedHits = {
            {
                start = 1.399999976158142, 
                multiplier = 1, 
                stop = 5
            }
        }
    }, 
    PrehistoricKrabs = {
        animationTime = 1.600000023841858, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.600000023841858
            }
        }
    }, 
    GrannyTentacles = {
        animationTime = 2.200000047683716, 
        sustainedHits = {
            {
                start = 0.8666666746139526, 
                multiplier = 1, 
                stop = 2.200000047683716
            }
        }
    }, 
    HandsomePlankton = {
        animationTime = 1.75, 
        sustainedHits = {
            {
                start = 0.8500000238418579, 
                multiplier = 1, 
                stop = 1.75
            }
        }
    }, 
    RealPioneerRock = {
        animationTime = 5.683333396911621, 
        sustainedHits = {
            {
                start = 0.4833333194255829, 
                multiplier = 1, 
                stop = 5.683333396911621
            }
        }
    }, 
    KarateSandy = {
        animationTime = 1.350000023841858, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.350000023841858
            }
        }
    }, 
    PioneerRock = {
        animationTime = 5.683333396911621, 
        sustainedHits = {
            {
                start = 0.4833333194255829, 
                multiplier = 1, 
                stop = 5.683333396911621
            }
        }
    }, 
    Richard = {
        animationTime = 2.1666667461395264, 
        sustainedHits = {
            {
                start = 0.800000011920929, 
                multiplier = 1, 
                stop = 2.1666667461395264
            }
        }
    }, 
    DrGillGilliam = {
        animationTime = 3.1666667461395264, 
        sustainedHits = {
            {
                start = 1.6333333253860474, 
                multiplier = 1, 
                stop = 3.1666667461395264
            }
        }
    }, 
    RustyRickets = {
        animationTime = 7.883333206176758, 
        singleHits = {
            {
                multiplier = 1, 
                time = 4.416666507720947
            }
        }, 
        sustainedHits = {
            {
                start = 5.7833333015441895, 
                multiplier = 1, 
                stop = 7.883333206176758
            }
        }
    }, 
    SnowSponge = {
        animationTime = 2.75, 
        sustainedHits = {
            {
                start = 1.8333333730697632, 
                multiplier = 1, 
                stop = 2.75
            }
        }
    }, 
    MimicBob = {
        animationTime = 3, 
        sustainedHits = {
            {
                start = 0.5425000190734863, 
                multiplier = 1, 
                stop = 3
            }
        }
    }, 
    Dorudon = {
        animationTime = 3.299999952316284, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.4879167079925537
            }
        }, 
        sustainedHits = {
            {
                start = 1.5554167032241821, 
                multiplier = 1, 
                stop = 3.299999952316284
            }
        }
    }, 
    BubblePoppinBoys = {
        animationTime = 1.150416612625122, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.150416612625122
            }
        }
    }, 
    BandSquidward = {
        animationTime = 3.366666555404663, 
        sustainedHits = {
            {
                start = 0, 
                multiplier = 0.1, 
                stop = 1.1833332777023315
            }, 
            {
                start = 1.2000000476837158, 
                multiplier = 0.35, 
                stop = 1.8166667222976685
            }, 
            {
                start = 1.8333333730697632, 
                multiplier = 0.5, 
                stop = 2.7666666507720947
            }, 
            {
                start = 2.7833333015441895, 
                multiplier = 1, 
                stop = 3.366666555404663
            }
        }
    }, 
    Bubbles = {
        animationTime = 2.1666667461395264, 
        sustainedHits = {
            {
                start = 1.1333333253860474, 
                multiplier = 1, 
                stop = 2.1666667461395264
            }
        }
    }, 
    SeaRhino = {
        animationTime = 1.5666667222976685, 
        sustainedHits = {
            {
                start = 1, 
                multiplier = 1, 
                stop = 1.5666667222976685
            }
        }
    }, 
    MegaHydraKaren = {
        animationTime = 5.333333492279053, 
        sustainedHits = {
            {
                start = 2.6666667461395264, 
                multiplier = 1, 
                stop = 5.333333492279053
            }
        }
    }, 
    Tiff = {
        animationTime = 1.8666666746139526, 
        sustainedHits = {
            {
                start = 1.2333333492279053, 
                multiplier = 1, 
                stop = 1.8666666746139526
            }
        }
    }, 
    BubbleBuddy = {
        animationTime = 2.8499999046325684, 
        sustainedHits = {
            {
                start = 0.6166666746139526, 
                multiplier = 1, 
                stop = 2.8499999046325684
            }
        }
    }, 
    Jim = {
        animationTime = 2.133333444595337, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.133333444595337
            }
        }
    }, 
    GGRockSpongebob = {
        animationTime = 4.2833333015441895, 
        sustainedHits = {
            {
                start = 2.133333444595337, 
                multiplier = 1, 
                stop = 4.2833333015441895
            }
        }
    }, 
    DreamPatrick = {
        animationTime = 2, 
        sustainedHits = {
            {
                start = 1.5833333730697632, 
                multiplier = 1, 
                stop = 2
            }
        }
    }, 
    CyborgPlankton = {
        animationTime = 1.2333333492279053, 
        sustainedHits = {
            {
                start = 0.6000000238418579, 
                multiplier = 1, 
                stop = 1.2333333492279053
            }
        }
    }, 
    BandSpongebob = {
        animationTime = 4.583333492279053, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.9666666388511658
            }
        }, 
        sustainedHits = {
            {
                start = 0.9666666388511658, 
                multiplier = 0.075, 
                stop = 2.116666555404663
            }, 
            {
                start = 2.133333444595337, 
                multiplier = 1, 
                stop = 4.583333492279053
            }
        }
    }, 
    FilthyBoys = {
        animationTime = 2.066666603088379, 
        sustainedHits = {
            {
                start = 0.5758333206176758, 
                multiplier = 1, 
                stop = 2.066666603088379
            }
        }
    }, 
    TheAppetizer = {
        animationTime = 3.1666667461395264, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.399999976158142
            }
        }, 
        sustainedHits = {
            {
                start = 1.399999976158142, 
                multiplier = 1, 
                stop = 3.1666667461395264
            }
        }
    }, 
    Pearl = {
        animationTime = 2.700000047683716, 
        sustainedHits = {
            {
                start = 1.7833333015441895, 
                multiplier = 1, 
                stop = 2.700000047683716
            }
        }
    }, 
    SeaBear = {
        animationTime = 2.5166666507720947, 
        sustainedHits = {
            {
                start = 0.3333333432674408, 
                multiplier = 1, 
                stop = 2.5166666507720947
            }
        }
    }, 
    MadameHagfish = {
        animationTime = 1.1666666269302368, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.3499999940395355
            }
        }, 
        sustainedHits = {
            {
                start = 0.28333333134651184, 
                multiplier = 1, 
                stop = 1.1666666269302368
            }
        }
    }, 
    BrokenSquidward = {
        animationTime = 3.200000047683716, 
        sustainedHits = {
            {
                start = 1.9666666984558105, 
                multiplier = 1, 
                stop = 3.200000047683716
            }
        }
    }, 
    EasterBunnySpongebob = {
        animationTime = 4.366666793823242, 
        sustainedHits = {
            {
                start = 3.933333396911621, 
                multiplier = 1, 
                stop = 4.366666793823242
            }
        }
    }, 
    BandPatrick = {
        animationTime = 3.0166666507720947, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.7999999523162842
            }, 
            {
                multiplier = 1, 
                time = 2.4000000953674316
            }, 
            {
                multiplier = 1, 
                time = 3.0166666507720947
            }
        }
    }, 
    BandSandy = {
        animationTime = 5.166666507720947, 
        sustainedHits = {
            {
                start = 1.1333333253860474, 
                multiplier = 1, 
                stop = 5.166666507720947
            }
        }
    }, 
    SantaClaus = {
        animationTime = 2.3333332538604736, 
        sustainedHits = {
            {
                start = 1.4166666269302368, 
                multiplier = 1, 
                stop = 2.3333332538604736
            }
        }
    }, 
    LordPoltergeist = {
        animationTime = 1.3166667222976685, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.3166667222976685
            }
        }
    }, 
    DreamGary = {
        animationTime = 3.6666667461395264, 
        sustainedHits = {
            {
                start = 1.1333333253860474, 
                multiplier = 1, 
                stop = 3.6666667461395264
            }
        }
    }, 
    SoaringStarfish = {
        animationTime = 5.583333492279053, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.25
            }, 
            {
                multiplier = 1, 
                time = 3.4166667461395264
            }, 
            {
                multiplier = 1, 
                time = 4.599999904632568
            }, 
            {
                multiplier = 1, 
                time = 5.583333492279053
            }
        }
    }, 
    CaptainMagma = {
        animationTime = 3.5, 
        sustainedHits = {
            {
                start = 0.8833333253860474, 
                multiplier = 1, 
                stop = 3.5
            }
        }
    }, 
    GoofyGooberWaiter = {
        animationTime = 2.133333444595337, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.133333444595337
            }
        }
    }, 
    BarnacleBoyPatrick = {
        animationTime = 2.25, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.25
            }
        }
    }, 
    FlyingDutchman = {
        animationTime = 2.049999952316284, 
        sustainedHits = {
            {
                start = 0.8833333253860474, 
                multiplier = 1, 
                stop = 2.049999952316284
            }
        }
    }, 
    GrandmaSquarePants = {
        animationTime = 2.616666555404663, 
        sustainedHits = {
            {
                start = 0.6000000238418579, 
                multiplier = 1, 
                stop = 2.616666555404663
            }
        }
    }, 
    TheSquarePants = {
        animationTime = 3.700000047683716, 
        sustainedHits = {
            {
                start = 1.1666666269302368, 
                multiplier = 1, 
                stop = 3.700000047683716
            }
        }
    }, 
    Spongehenge = {
        animationTime = 3, 
        sustainedHits = {
            {
                start = 1.1666666269302368, 
                multiplier = 1, 
                stop = 3
            }
        }
    }, 
    SmittyWerbenjagermanjensen = {
        animationTime = 2, 
        sustainedHits = {
            {
                start = 0, 
                multiplier = 1, 
                stop = 2
            }
        }
    }, 
    Marina = {
        animationTime = 2.5, 
        sustainedHits = {
            {
                start = 1.125, 
                multiplier = 1, 
                stop = 2.5
            }
        }
    }, 
    Quickster = {
        animationTime = 4.150000095367432, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0
            }, 
            {
                multiplier = 1, 
                time = 0.3499999940395355
            }, 
            {
                multiplier = 1, 
                time = 0.7333333492279053
            }, 
            {
                multiplier = 1, 
                time = 1.149999976158142
            }, 
            {
                multiplier = 1, 
                time = 1.5
            }, 
            {
                multiplier = 1, 
                time = 1.850000023841858
            }, 
            {
                multiplier = 1, 
                time = 2.2333333492279053
            }, 
            {
                multiplier = 1, 
                time = 2.6500000953674316
            }, 
            {
                multiplier = 1, 
                time = 3
            }, 
            {
                multiplier = 1, 
                time = 3.3499999046325684
            }, 
            {
                multiplier = 1, 
                time = 3.7333333492279053
            }, 
            {
                multiplier = 1, 
                time = 4.150000095367432
            }
        }
    }, 
    KaptainPlankton = {
        animationTime = 5, 
        sustainedHits = {
            {
                start = 1.4583333730697632, 
                multiplier = 1, 
                stop = 5
            }
        }
    }, 
    HandsomeSquidward = {
        animationTime = 3.0333333015441895, 
        sustainedHits = {
            {
                start = 1.9666666984558105, 
                multiplier = 1, 
                stop = 3.0333333015441895
            }
        }
    }, 
    TexasSandy = {
        animationTime = 1.75, 
        sustainedHits = {
            {
                start = 1.2000000476837158, 
                multiplier = 1, 
                stop = 1.75
            }
        }
    }, 
    BabyPrunes = {
        animationTime = 4.266666889190674, 
        sustainedHits = {
            {
                start = 2.5999999046325684, 
                multiplier = 1, 
                stop = 4.266666889190674
            }
        }
    }, 
    Wormy = {
        animationTime = 3.5999999046325684, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.2333333492279053
            }
        }, 
        sustainedHits = {
            {
                start = 2.0999999046325684, 
                multiplier = 1, 
                stop = 3.5999999046325684
            }
        }
    }, 
    GloveyGlove = {
        animationTime = 1.6666666269302368, 
        sustainedHits = {
            {
                start = 0.6816666722297668, 
                multiplier = 1, 
                stop = 1.6666666269302368
            }
        }
    }, 
    BuffSandy = {
        animationTime = 3.200000047683716, 
        sustainedHits = {
            {
                start = 2.450000047683716, 
                multiplier = 1, 
                stop = 3.200000047683716
            }
        }
    }, 
    KampSpongebob = {
        animationTime = 3.1666667461395264, 
        sustainedHits = {
            {
                start = 1.6666666269302368, 
                multiplier = 1, 
                stop = 3.1666667461395264
            }
        }
    }, 
    Nocturna = {
        animationTime = 4.2833333015441895, 
        sustainedHits = {
            {
                start = 2.0333333015441895, 
                multiplier = 1, 
                stop = 4.2833333015441895
            }
        }
    }, 
    PlanktonTankRobot = {
        animationTime = 1.899999976158142, 
        sustainedHits = {
            {
                start = 1.0666667222976685, 
                multiplier = 1, 
                stop = 1.899999976158142
            }
        }
    }, 
    ManRay = {
        animationTime = 4.766666889190674, 
        sustainedHits = {
            {
                start = 3.4000000953674316, 
                multiplier = 1, 
                stop = 4.766666889190674
            }
        }
    }, 
    KampSquidward = {
        animationTime = 3.5, 
        sustainedHits = {
            {
                start = 1.7000000476837158, 
                multiplier = 1, 
                stop = 3.5
            }
        }
    }, 
    Harold = {
        animationTime = 1.25, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.25
            }
        }
    }, 
    Sandy = {
        animationTime = 0.7666666507720947, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.7666666507720947
            }
        }
    }, 
    MrSuperAwesomeness = {
        animationTime = 4.458333492279053, 
        sustainedHits = {
            {
                start = 0.9583333134651184, 
                multiplier = 1, 
                stop = 4.458333492279053
            }
        }
    }, 
    Clamu = {
        animationTime = 2.9000000953674316, 
        sustainedHits = {
            {
                start = 1.4333332777023315, 
                multiplier = 1, 
                stop = 2.9000000953674316
            }
        }
    }, 
    Invincibubble = {
        animationTime = 2.133333444595337, 
        sustainedHits = {
            {
                start = 0.6333333253860474, 
                multiplier = 1, 
                stop = 2.133333444595337
            }
        }
    }, 
    KingKrabs = {
        animationTime = 3.5, 
        sustainedHits = {
            {
                start = 1.8833333253860474, 
                multiplier = 1, 
                stop = 3.5
            }
        }
    }, 
    KampSandy = {
        animationTime = 2.200000047683716, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.200000047683716
            }
        }
    }, 
    MamaBass = {
        animationTime = 2.875, 
        sustainedHits = {
            {
                start = 0.875, 
                multiplier = 1, 
                stop = 2.875
            }
        }
    }, 
    SpongebobSanta = {
        animationTime = 2.5, 
        sustainedHits = {
            {
                start = 2.0833332538604736, 
                multiplier = 1, 
                stop = 2.5
            }
        }
    }, 
    ArmyOfTheLivingDead = {
        animationTime = 2.450000047683716, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.6808333396911621
            }, 
            {
                multiplier = 1, 
                time = 0.7233333587646484
            }
        }, 
        sustainedHits = {
            {
                start = 0.8083333373069763, 
                multiplier = 1, 
                stop = 1.6333333253860474
            }
        }
    }, 
    KampPearl = {
        animationTime = 2.6666667461395264, 
        sustainedHits = {
            {
                start = 1.6666666269302368, 
                multiplier = 1, 
                stop = 2.6666667461395264
            }
        }
    }, 
    PatTheHapless = {
        animationTime = 0.6833333373069763, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.6833333373069763
            }
        }
    }, 
    PaintyThePirate = {
        animationTime = 4.833333492279053, 
        sustainedHits = {
            {
                start = 2.241666555404663, 
                multiplier = 1, 
                stop = 4.833333492279053
            }
        }
    }, 
    Dennis = {
        animationTime = 5.316666603088379, 
        sustainedHits = {
            {
                start = 2.25, 
                multiplier = 1, 
                stop = 5.316666603088379
            }
        }
    }, 
    AtomicFlounder = {
        animationTime = 1.2000000476837158, 
        sustainedHits = {
            {
                start = 0.28333333134651184, 
                multiplier = 1, 
                stop = 1.2000000476837158
            }
        }
    }, 
    Squidward = {
        animationTime = 5, 
        sustainedHits = {
            {
                start = 0, 
                multiplier = 1, 
                stop = 5
            }
        }
    }, 
    BarnacleBoy = {
        animationTime = 3.9000000953674316, 
        singleHits = {
            {
                multiplier = 1, 
                time = 1.0166666507720947
            }
        }, 
        sustainedHits = {
            {
                start = 2.5, 
                multiplier = 0.067, 
                stop = 3.9000000953674316
            }
        }
    }, 
    KingOfKarate = {
        animationTime = 4, 
        sustainedHits = {
            {
                start = 2.450000047683716, 
                multiplier = 1, 
                stop = 4
            }
        }
    }, 
    Patrick = {
        animationTime = 2.049999952316284, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.049999952316284
            }
        }
    }, 
    SwashbucklerKrabs = {
        animationTime = 2.625, 
        sustainedHits = {
            {
                start = 0.7649999856948853, 
                multiplier = 1, 
                stop = 2.625
            }
        }
    }, 
    BigGuySpongebob = {
        animationTime = 0.9833333492279053, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.9833333492279053
            }
        }
    }, 
    CavemanSpongebob = {
        animationTime = 2.2833333015441895, 
        singleHits = {
            {
                multiplier = 1, 
                time = 2.2833333015441895
            }
        }
    }, 
    MrsPuff = {
        animationTime = 2.066666603088379, 
        sustainedHits = {
            {
                start = 0.5166666507720947, 
                multiplier = 1, 
                stop = 2.066666603088379
            }
        }
    }, 
    BubblePoppinThug2 = {
        animationTime = 1, 
        sustainedHits = {
            {
                start = 0.4166666567325592, 
                multiplier = 1, 
                stop = 1
            }
        }
    }, 
    ChumBrute = {
        animationTime = 1.4833333492279053, 
        singleHits = {
            {
                multiplier = 1, 
                time = 0.8833333253860474
            }, 
            {
                multiplier = 1, 
                time = 1.4833333492279053
            }
        }
    }, 
    CommandModule = {
        animationTime = 3.200000047683716, 
        sustainedHits = {
            {
                start = 1.1333333253860474, 
                multiplier = 1, 
                stop = 3.200000047683716
            }
        }
    }, 
    ToyBob = {
        animationTime = 3.299999952316284, 
        sustainedHits = {
            {
                start = 1.3833333253860474, 
                multiplier = 1, 
                stop = 3.299999952316284
            }
        }
    }, 
    HashSlingingSlasher = {
        animationTime = 3, 
        singleHits = {
            {
                multiplier = 0.5, 
                time = 0.550000011920929
            }, 
            {
                multiplier = 0.5, 
                time = 0.8333333134651184
            }
        }, 
        sustainedHits = {
            {
                start = 2.433333396911621, 
                multiplier = 1, 
                stop = 3
            }
        }
    }
};