return {
    SnowMolluskFix = {
        awardOnce = true, 
        rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 5
            }, 
            {
                type = "Unit", 
                name = "SnowMollusk", 
                amount = 1, 
                noDisplay = true
            }
        }
    }, 
    SeasonPassSkipsFix = {
        awardOnce = true, 
        rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 5000
            }
        }
    }, 
    InfluencerCarePackage1 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Currency", 
                name = "Coins", 
                amount = 100000
            }, 
            {
                type = "Inventory", 
                name = "TreasureChest", 
                amount = 25
            }
        }
    }, 
    QuestsFix = {
        awardOnce = true, 
        rewards = {
            {
                type = "Inventory", 
                name = "TreasureChest", 
                amount = 25
            }
        }
    }, 
    InfluencerCarePackage2 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Inventory", 
                name = "MythicTreasureChest", 
                amount = 5
            }, 
            {
                type = "Currency", 
                name = "Gems", 
                amount = 2500
            }
        }
    }, 
    PrestigeSecretUnitFix = {
        awardOnce = true, 
        rewards = {
            {
                type = "Unit", 
                name = "Spongehenge", 
                amount = 1, 
                noDisplay = true
            }
        }
    }, 
    InfluencerCarePackage5 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Currency", 
                name = "MagicConch", 
                amount = 100
            }
        }
    }, 
    ModCarePackage1 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Currency", 
                name = "GoldenTraitRolls", 
                amount = 50
            }, 
            {
                type = "Inventory", 
                name = "GIFT_UltraVIP", 
                amount = 1
            }, 
            {
                type = "Inventory", 
                name = "GIFT_TreasureHunter", 
                amount = 1
            }, 
            {
                type = "Inventory", 
                name = "SecretTreasureChest", 
                amount = 5
            }, 
            {
                type = "Currency", 
                name = "Coins", 
                amount = 20000
            }
        }
    }, 
    InvestorCarePackage1 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Unit", 
                name = "Spongehenge", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "CavemanSpongebob", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "SoaringStarfish", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "GGRockSpongebob", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "CaptainMagma", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "Quickster", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "CyborgPlankton", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Unit", 
                name = "DreamGary", 
                amount = 1, 
                noDisplay = true
            }, 
            {
                type = "Inventory", 
                name = "BoxChocolates2025", 
                amount = 100
            }
        }
    }, 
    SummonBugFix = {
        awardOnce = true, 
        rewards = {
            {
                type = "Currency", 
                name = "Gems", 
                amount = 10000
            }, 
            {
                type = "Currency", 
                name = "MagicConch", 
                amount = 10
            }
        }
    }, 
    KrustyKrewDailyFix = {
        awardOnce = true, 
        rewards = {
            {
                type = "Inventory", 
                name = "SecretTreasureChest", 
                amount = 1
            }
        }
    }, 
    ModCarePackage2 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Inventory", 
                name = "DragonEgg", 
                amount = 5
            }, 
            {
                type = "Inventory", 
                name = "GIFT_2xFoodDrops", 
                amount = 1
            }
        }
    }, 
    InvestorCarePackage2 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Inventory", 
                name = "DragonEgg", 
                amount = 5
            }, 
            {
                type = "Inventory", 
                name = "ChallengeGift", 
                amount = 10
            }, 
            {
                type = "Inventory", 
                name = "SecretTreasureChest", 
                amount = 3
            }, 
            {
                type = "Currency", 
                name = "Gems", 
                amount = 25000
            }, 
            {
                type = "Currency", 
                name = "MagicConch", 
                amount = 100
            }, 
            {
                type = "Currency", 
                name = "GoldenTraitRolls", 
                amount = 100
            }
        }
    }, 
    GTD_Rewards1 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Inventory", 
                name = "ExoticTreasureChest", 
                amount = 10
            }
        }
    }, 
    GTD_Rewards2 = {
        awardOnce = true, 
        rewards = {
            {
                type = "Unit", 
                name = "KaptainPlankton", 
                amount = 1, 
                noDisplay = true
            }
        }
    }, 
    MOVIE_ITEMS = {
        awardOnce = false, 
        rewards = {
            {
                type = "Inventory", 
                name = "ExoticTreasureChest", 
                amount = 1
            }, 
            {
                type = "Inventory", 
                name = "GIFT_x2Leveling", 
                amount = 1
            }
        }
    }, 
    ChristmasTree2025 = {
        awardOnce = false, 
        rewards = {
            {
                type = "Inventory", 
                name = "CoralGift", 
                amount = 1
            }
        }
    }, 
    SBBDay100Reward = {
        awardOnce = true, 
        rewards = {
            {
                type = "Unit", 
                name = "Nat", 
                amount = 1, 
                noDisplay = true
            }
        }
    }
};