local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = game:GetService("RunService");
local _ = require(l_ReplicatedStorage_0.Shared.Data.Purchases);
return {
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 1
        }, 
        freeAmount = 0, 
        purchaseName = "DNDPack1"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 3
        }, 
        freeAmount = 1, 
        purchaseName = "DNDPack2"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 5
        }, 
        freeAmount = 2, 
        purchaseName = "DNDPack3"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 10
        }, 
        freeAmount = 5, 
        purchaseName = "DNDPack4"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 25
        }, 
        freeAmount = 15, 
        purchaseName = "DNDPack5"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 50
        }, 
        freeAmount = 25, 
        purchaseName = "DNDPack6"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 100
        }, 
        freeAmount = 50, 
        purchaseName = "DNDPack7"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "DragonEgg", 
            amount = 200
        }, 
        freeAmount = 100, 
        purchaseName = "DNDPack8"
    }
};