return {
    VariantsPool = {
        Normal = {
            weight = 95
        }, 
        Shiny = {
            weight = 3
        }, 
        Wumbo = {
            weight = 1.5
        }, 
        ShinyWumbo = {
            weight = 0.5
        }
    }, 
    RaritiesPool = {
        Rare = {
            weight = 45
        }, 
        Epic = {
            weight = 30
        }, 
        Legendary = {
            weight = 23.5
        }, 
        Mythic = {
            weight = 1.4
        }, 
        Secret = {
            weight = 0.1
        }
    }, 
    LootPool = {
        Rare = {
            {
                type = "Unit", 
                name = "SquidlyTentacles", 
                extraData = {}, 
                amount = 1, 
                weight = 45
            }
        }, 
        Epic = {
            {
                type = "Unit", 
                name = "PrincessPearl", 
                extraData = {}, 
                amount = 1, 
                weight = 30
            }
        }, 
        Legendary = {
            {
                type = "Unit", 
                name = "SirPatrick", 
                extraData = {}, 
                amount = 1, 
                weight = 13.5
            }, 
            {
                type = "Unit", 
                name = "DarkKnight", 
                extraData = {}, 
                amount = 1, 
                weight = 10
            }
        }, 
        Mythic = {
            {
                type = "Unit", 
                name = "SirSpongebob", 
                extraData = {}, 
                amount = 1, 
                weight = 1.4
            }
        }, 
        Secret = {
            {
                type = "Unit", 
                name = "DungeonMaster", 
                extraData = {}, 
                amount = 1, 
                weight = 0.1
            }
        }
    }
};