return {
    VariantsPool = {
        Normal = {
            weight = 85
        }, 
        Shiny = {
            weight = 9
        }, 
        Wumbo = {
            weight = 5
        }, 
        ShinyWumbo = {
            weight = 1
        }
    }, 
    RaritiesPool = {
        Limited = {
            weight = 100
        }
    }, 
    LootPool = {
        Limited = {
            {
                type = "Unit", 
                name = "EasterBunnySpongebob", 
                extraData = {}, 
                amount = 1, 
                weight = 100
            }
        }
    }
};