return {
    ShopOrder = 3, 
    Cost = {
        currencyName = "MagicConch", 
        price = 1
    }, 
    Pool = {
        RaritiesPool = {
            Rare = {
                weight = 75, 
                shinyWeight = 1, 
                megaWeight = 0.5, 
                megaShinyWeight = 0.25
            }, 
            Epic = {
                weight = 21, 
                shinyWeight = 0.5, 
                megaWeight = 0.25, 
                megaShinyWeight = 0.125
            }, 
            Legendary = {
                weight = 3.5, 
                shinyWeight = 0.25, 
                megaWeight = 0.1, 
                megaShinyWeight = 0.09
            }, 
            Mythic = {
                weight = 0.46, 
                shinyWeight = 0.1, 
                megaWeight = 0.05, 
                megaShinyWeight = 0.035
            }, 
            Secret = {
                weight = 0.04, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }, 
            Exotic = {
                weight = 0.005, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }
        }, 
        UnitsPool = {
            Rare = {
                {
                    type = "Unit", 
                    name = "SlappyLaszlo", 
                    weight = 25
                }, 
                {
                    type = "Unit", 
                    name = "BubbleBuddy", 
                    weight = 25
                }, 
                {
                    type = "Unit", 
                    name = "SquilliamFancyson", 
                    weight = 25
                }
            }, 
            Epic = {
                {
                    type = "Unit", 
                    name = "AtomicFlounder", 
                    weight = 8
                }, 
                {
                    type = "Unit", 
                    name = "TexasSandy", 
                    weight = 7
                }, 
                {
                    type = "Unit", 
                    name = "BargNMart", 
                    weight = 6
                }
            }, 
            Legendary = {
                {
                    type = "Unit", 
                    name = "FlyingDutchman", 
                    weight = 2
                }, 
                {
                    type = "Unit", 
                    name = "DreamPatrick", 
                    weight = 1.5
                }
            }, 
            Mythic = {
                {
                    type = "Unit", 
                    name = "HibernationSandy", 
                    weight = 0.2
                }, 
                {
                    type = "Unit", 
                    name = "Quickster", 
                    weight = 0.16
                }, 
                {
                    type = "Unit", 
                    name = "Tattletale", 
                    weight = 0.1
                }
            }, 
            Secret = {
                {
                    type = "Unit", 
                    name = "DreamGary", 
                    weight = 0.022
                }, 
                {
                    type = "Unit", 
                    name = "AlaskanBullWorm", 
                    weight = 0.01
                }, 
                {
                    type = "Unit", 
                    name = "MrSuperAwesomeness", 
                    weight = 0.008
                }
            }, 
            Exotic = {
                {
                    type = "Unit", 
                    name = "JellienLeader", 
                    weight = 0.005
                }
            }
        }
    }
};