local v0 = {
    Config = {
        ENEMY_HEALTH_BUFF_PER_FLOOR = 1.05
    }, 
    FloorConfigs = {}
};
v0.FloorConfigs[1] = {
    EnemyConfig = {
        DamageMult = 1, 
        HealthMult = 1.25
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 4, 
            Damage = 2, 
            Scale = 1.56, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[2] = {
    EnemyConfig = {
        DamageMult = 1.01, 
        HealthMult = 1.36
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.3, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 2, 
            Damage = 2, 
            Scale = 1.75, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.5, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[3] = {
    EnemyConfig = {
        DamageMult = 1.02, 
        HealthMult = 1.68
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 5, 
            Damage = 2, 
            Scale = 1.56, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[4] = {
    EnemyConfig = {
        DamageMult = 1.03, 
        HealthMult = 2.22
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 6, 
            Damage = 2, 
            Scale = 1.1, 
            WalkSpeed = 16, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 11, 
            Delay = NumberRange.new(0.1, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[5] = {
    EnemyConfig = {
        DamageMult = 1.04, 
        HealthMult = 2.98
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 4, 
            Damage = 2, 
            Scale = 1.43, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 1, 
            Damage = 2, 
            Scale = 1.95, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(1, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[6] = {
    EnemyConfig = {
        DamageMult = 1.05, 
        HealthMult = 3.95
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 7, 
            Damage = 2, 
            Scale = 1.17, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.1, 1.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[7] = {
    EnemyConfig = {
        DamageMult = 1.06, 
        HealthMult = 5.14
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.75, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.3, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 1.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[8] = {
    EnemyConfig = {
        DamageMult = 1.07, 
        HealthMult = 6.54
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 8, 
            Damage = 2, 
            Scale = 1.04, 
            WalkSpeed = 18, 
            AttackCooldown = 2, 
            AttackSpeed = 1.4, 
            AttackRange = 14, 
            AggroRange = 11, 
            Delay = NumberRange.new(0.1, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[9] = {
    EnemyConfig = {
        DamageMult = 1.08, 
        HealthMult = 8.16
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 2, 
            Damage = 2, 
            Scale = 1.95, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(1, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 4, 
            Damage = 2, 
            Scale = 1.43, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 1.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[10] = {
    EnemyConfig = {
        DamageMult = 1.09, 
        HealthMult = 10
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 10, 
            Scale = 3.2, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 10, 
            Damage = 2, 
            Scale = 1.3, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.1, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.1, 
            WalkSpeed = 8, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[11] = {
    EnemyConfig = {
        DamageMult = 1.1, 
        HealthMult = 5
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.17, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.2, 
            WalkSpeed = 7, 
            AttackCooldown = 2, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[12] = {
    EnemyConfig = {
        DamageMult = 1.11, 
        HealthMult = 5.06
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            Damage = 9, 
            Scale = 1.3, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 4, 
            Damage = 2, 
            Scale = 1.1, 
            WalkSpeed = 16, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.1, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[13] = {
    EnemyConfig = {
        DamageMult = 1.12, 
        HealthMult = 5.25
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateBruiser", 
            Amount = 3, 
            Damage = 9, 
            Scale = 0.9, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[14] = {
    EnemyConfig = {
        DamageMult = 1.13, 
        HealthMult = 5.56
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 8, 
            Damage = 2, 
            Scale = 0.97, 
            WalkSpeed = 20, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 11, 
            Delay = NumberRange.new(0.1, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[15] = {
    EnemyConfig = {
        DamageMult = 1.14, 
        HealthMult = 5.99
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.3, 
            WalkSpeed = 6.5, 
            AttackCooldown = 2, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.43, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 1.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[16] = {
    EnemyConfig = {
        DamageMult = 1.15, 
        HealthMult = 6.54
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 9, 
            Scale = 1, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.3, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 9, 
            Scale = 1, 
            WalkSpeed = 8, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[17] = {
    EnemyConfig = {
        DamageMult = 1.16, 
        HealthMult = 7.22
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 10, 
            Damage = 2, 
            Scale = 0.97, 
            WalkSpeed = 22, 
            AttackCooldown = 2, 
            AttackSpeed = 1.6, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.1, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[18] = {
    EnemyConfig = {
        DamageMult = 1.17, 
        HealthMult = 8.02
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 3, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.8, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 9, 
            Scale = 0.85, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.2, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[19] = {
    EnemyConfig = {
        DamageMult = 1.18, 
        HealthMult = 8.95
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.5, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(1, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 5, 
            Damage = 2, 
            Scale = 1.3, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[20] = {
    EnemyConfig = {
        DamageMult = 1.19, 
        HealthMult = 10
    }, 
    Enemies = {
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 12, 
            Scale = 2, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 8, 
            Damage = 2, 
            Scale = 1.3, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.1, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.1, 
            WalkSpeed = 8, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            Damage = 9, 
            Scale = 1.2, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.6, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.4, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[21] = {
    EnemyConfig = {
        DamageMult = 1.2, 
        HealthMult = 10
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 1, 
            Damage = 6, 
            Scale = 1.3, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 0.8, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 4, 
            Damage = 2, 
            Scale = 1.17, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.1, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[22] = {
    EnemyConfig = {
        DamageMult = 1.21, 
        HealthMult = 10.06
    }, 
    Enemies = {
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 11, 
            Scale = 0.85, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 9, 
            Scale = 1.1, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1.6, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.4, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[23] = {
    EnemyConfig = {
        DamageMult = 1.22, 
        HealthMult = 10.25
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 3, 
            Damage = 6, 
            Scale = 0.85, 
            WalkSpeed = 12, 
            AttackCooldown = 3, 
            AttackSpeed = 1.2, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 1, 
            Damage = 6, 
            Scale = 1.35, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.7, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[24] = {
    EnemyConfig = {
        DamageMult = 1.23, 
        HealthMult = 10.56
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 6, 
            Damage = 2, 
            Scale = 0.97, 
            WalkSpeed = 20, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 11, 
            Delay = NumberRange.new(0.1, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[25] = {
    EnemyConfig = {
        DamageMult = 1.24, 
        HealthMult = 10.99
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.4, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.8, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 0.9, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1.4, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[26] = {
    EnemyConfig = {
        DamageMult = 1.25, 
        HealthMult = 11.54
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 5, 
            Damage = 6, 
            Scale = 0.8, 
            WalkSpeed = 13, 
            AttackCooldown = 3, 
            AttackSpeed = 1.3, 
            AttackRange = 17, 
            AggroRange = 18, 
            Delay = NumberRange.new(0.2, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[27] = {
    EnemyConfig = {
        DamageMult = 1.26, 
        HealthMult = 12.22
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 4, 
            Damage = 9, 
            Scale = 1.2, 
            WalkSpeed = 7, 
            AttackCooldown = 2, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1, 
            WalkSpeed = 10, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[28] = {
    EnemyConfig = {
        DamageMult = 1.27, 
        HealthMult = 13.02
    }, 
    Enemies = {
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.3, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 9, 
            Scale = 0.9, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 2.2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.43, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.3, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[29] = {
    EnemyConfig = {
        DamageMult = 1.28, 
        HealthMult = 13.95
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1.35, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.7, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 3, 
            Damage = 6, 
            Scale = 0.9, 
            WalkSpeed = 12, 
            AttackCooldown = 3, 
            AttackSpeed = 1.2, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[30] = {
    EnemyConfig = {
        DamageMult = 1.29, 
        HealthMult = 15
    }, 
    Enemies = {
        {
            Name = "TheTickler", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 12, 
            Scale = 3.2, 
            WalkSpeed = 12, 
            AttackCooldown = 4, 
            AttackSpeed = 1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[31] = {
    EnemyConfig = {
        DamageMult = 1.3, 
        HealthMult = 12
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 2, 
            Damage = 5, 
            Scale = 1.3, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.8, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 2, 
            Damage = 6, 
            Scale = 0.85, 
            WalkSpeed = 18, 
            AttackCooldown = 2, 
            AttackSpeed = 2.3, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 3, 
            Damage = 2, 
            Scale = 1.3, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 9, 
            Delay = NumberRange.new(0.2, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[32] = {
    EnemyConfig = {
        DamageMult = 1.31, 
        HealthMult = 12.05
    }, 
    Enemies = {
        {
            Name = "TheTickler", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.3, 
            WalkSpeed = 11, 
            AttackCooldown = 4, 
            AttackSpeed = 0.9, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 0.85, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.2, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[33] = {
    EnemyConfig = {
        DamageMult = 1.32, 
        HealthMult = 12.2
    }, 
    Enemies = {
        {
            Name = "KarateAssassin", 
            Amount = 4, 
            Damage = 6, 
            Scale = 1, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 2, 
            Damage = 5, 
            Scale = 1.2, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[34] = {
    EnemyConfig = {
        DamageMult = 1.33, 
        HealthMult = 12.44
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 3, 
            Damage = 9, 
            Scale = 1.1, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1.7, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.3, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1.2, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[35] = {
    EnemyConfig = {
        DamageMult = 1.34, 
        HealthMult = 12.79
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 1, 
            Damage = 5, 
            Scale = 1.35, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 5, 
            Damage = 6, 
            Scale = 0.8, 
            WalkSpeed = 20, 
            AttackCooldown = 2, 
            AttackSpeed = 2.5, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.1, 0.4), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[36] = {
    EnemyConfig = {
        DamageMult = 1.35, 
        HealthMult = 13.23
    }, 
    Enemies = {
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.1, 
            WalkSpeed = 13, 
            AttackCooldown = 4, 
            AttackSpeed = 1.1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.3, 0.7), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 11, 
            Scale = 1.2, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.8, 1.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KimonoAnchovy", 
            Amount = 4, 
            Damage = 2, 
            Scale = 1.17, 
            WalkSpeed = 16, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.1, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[37] = {
    EnemyConfig = {
        DamageMult = 1.36, 
        HealthMult = 13.78
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 3, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 3, 
            Damage = 5, 
            Scale = 0.9, 
            WalkSpeed = 10, 
            AttackCooldown = 3, 
            AttackSpeed = 2.3, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[38] = {
    EnemyConfig = {
        DamageMult = 1.37, 
        HealthMult = 14.42
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.8, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.5, 
            WalkSpeed = 10, 
            AttackCooldown = 4, 
            AttackSpeed = 0.8, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 3, 
            Damage = 6, 
            Scale = 1, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[39] = {
    EnemyConfig = {
        DamageMult = 1.38, 
        HealthMult = 15.16
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 6, 
            Damage = 5, 
            Scale = 0.75, 
            WalkSpeed = 12, 
            AttackCooldown = 3, 
            AttackSpeed = 2.5, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[40] = {
    EnemyConfig = {
        DamageMult = 1.39, 
        HealthMult = 16
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 12, 
            Scale = 3, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 11, 
            Scale = 1, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[41] = {
    EnemyConfig = {
        DamageMult = 1.4, 
        HealthMult = 20
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 3, 
            Damage = 6, 
            Scale = 1.2, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 2, 
            Damage = 5, 
            Scale = 1.1, 
            WalkSpeed = 8.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.4, 0.9), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 2, 
            Damage = 6, 
            Scale = 0.9, 
            WalkSpeed = 17, 
            AttackCooldown = 2, 
            AttackSpeed = 2.2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[42] = {
    EnemyConfig = {
        DamageMult = 1.41, 
        HealthMult = 20.06
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 0.9, 
            WalkSpeed = 14, 
            AttackCooldown = 4, 
            AttackSpeed = 1.2, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[43] = {
    EnemyConfig = {
        DamageMult = 1.42, 
        HealthMult = 20.25
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 6, 
            Damage = 6, 
            Scale = 0.75, 
            WalkSpeed = 22, 
            AttackCooldown = 2, 
            AttackSpeed = 2.7, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[44] = {
    EnemyConfig = {
        DamageMult = 1.43, 
        HealthMult = 20.56
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 3, 
            Damage = 9, 
            Scale = 1, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1.1, 
            WalkSpeed = 10.5, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[45] = {
    EnemyConfig = {
        DamageMult = 1.44, 
        HealthMult = 20.99
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 4, 
            Damage = 5, 
            Scale = 1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1.35, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.7, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[46] = {
    EnemyConfig = {
        DamageMult = 1.45, 
        HealthMult = 21.54
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 0.85, 
            WalkSpeed = 10, 
            AttackCooldown = 3, 
            AttackSpeed = 1.2, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.3, 0.7), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 10, 
            AttackCooldown = 4, 
            AttackSpeed = 0.8, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 3, 
            Damage = 6, 
            Scale = 1, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[47] = {
    EnemyConfig = {
        DamageMult = 1.46, 
        HealthMult = 22.22
    }, 
    Enemies = {
        {
            Name = "KimonoAnchovy", 
            Amount = 10, 
            Damage = 2, 
            Scale = 1.26, 
            WalkSpeed = 25, 
            AttackCooldown = 2, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[48] = {
    EnemyConfig = {
        DamageMult = 1.47, 
        HealthMult = 23.02
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 9, 
            Scale = 1.2, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.6, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.6, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 3, 
            Damage = 5, 
            Scale = 0.85, 
            WalkSpeed = 10, 
            AttackCooldown = 3, 
            AttackSpeed = 2.3, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[49] = {
    EnemyConfig = {
        DamageMult = 1.48, 
        HealthMult = 23.95
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1, 
            WalkSpeed = 12, 
            AttackCooldown = 4, 
            AttackSpeed = 1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.4, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1.1, 
            WalkSpeed = 9.5, 
            AttackCooldown = 3, 
            AttackSpeed = 0.95, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[50] = {
    EnemyConfig = {
        DamageMult = 1.49, 
        HealthMult = 25
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 16, 
            Scale = 3, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 4, 
            AttackSpeed = 1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[51] = {
    EnemyConfig = {
        DamageMult = 1.5, 
        HealthMult = 25
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 3, 
            Damage = 9, 
            Scale = 1.2, 
            WalkSpeed = 7, 
            AttackCooldown = 2, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.7, 1.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 2, 
            Damage = 5, 
            Scale = 1.3, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.8, 1.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 3, 
            Damage = 6, 
            Scale = 0.9, 
            WalkSpeed = 17, 
            AttackCooldown = 2, 
            AttackSpeed = 2.2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[52] = {
    EnemyConfig = {
        DamageMult = 1.51, 
        HealthMult = 25.09
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 1, 
            Damage = 16, 
            Scale = 1.2, 
            WalkSpeed = 6, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 0.9, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.4, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[53] = {
    EnemyConfig = {
        DamageMult = 1.52, 
        HealthMult = 25.35
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 4, 
            Damage = 6, 
            Scale = 1, 
            WalkSpeed = 10, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.1, 
            WalkSpeed = 11, 
            AttackCooldown = 4, 
            AttackSpeed = 0.95, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[54] = {
    EnemyConfig = {
        DamageMult = 1.53, 
        HealthMult = 25.78
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 3, 
            Damage = 9, 
            Scale = 0.85, 
            WalkSpeed = 14, 
            AttackCooldown = 2, 
            AttackSpeed = 2.2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1.2, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[55] = {
    EnemyConfig = {
        DamageMult = 1.54, 
        HealthMult = 26.38
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 1, 
            Damage = 5, 
            Scale = 1.35, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.3, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 6, 
            Damage = 6, 
            Scale = 0.75, 
            WalkSpeed = 22, 
            AttackCooldown = 2, 
            AttackSpeed = 2.7, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[56] = {
    EnemyConfig = {
        DamageMult = 1.55, 
        HealthMult = 27.16
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 16, 
            Scale = 1, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 11, 
            AttackCooldown = 4, 
            AttackSpeed = 0.9, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[57] = {
    EnemyConfig = {
        DamageMult = 1.56, 
        HealthMult = 28.11
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 4, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 3, 
            Damage = 6, 
            Scale = 0.85, 
            WalkSpeed = 12, 
            AttackCooldown = 3, 
            AttackSpeed = 1.2, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[58] = {
    EnemyConfig = {
        DamageMult = 1.57, 
        HealthMult = 29.23
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.3, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.8, 1.4), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 3, 
            Damage = 11, 
            Scale = 0.9, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1.4, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.3, 0.7), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[59] = {
    EnemyConfig = {
        DamageMult = 1.58, 
        HealthMult = 30.53
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 1, 
            Damage = 16, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 3, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 0.9, 
            WalkSpeed = 13, 
            AttackCooldown = 4, 
            AttackSpeed = 1.1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[60] = {
    EnemyConfig = {
        DamageMult = 1.59, 
        HealthMult = 32
    }, 
    Enemies = {
        {
            Name = "LippCervas", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 8, 
            Scale = 2.6, 
            WalkSpeed = 4, 
            AttackCooldown = 1, 
            AttackSpeed = 3, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 4, 
            AttackSpeed = 1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.5, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[61] = {
    EnemyConfig = {
        DamageMult = 1.6, 
        HealthMult = 32
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 3, 
            Damage = 5, 
            Scale = 1.2, 
            WalkSpeed = 7.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.7, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 4, 
            Damage = 6, 
            Scale = 0.85, 
            WalkSpeed = 18, 
            AttackCooldown = 2, 
            AttackSpeed = 2.3, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.2, 0.4), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[62] = {
    EnemyConfig = {
        DamageMult = 1.61, 
        HealthMult = 32.07
    }, 
    Enemies = {
        {
            Name = "LippCervas", 
            Amount = 1, 
            Damage = 7, 
            Scale = 1.1, 
            WalkSpeed = 5, 
            AttackCooldown = 1, 
            AttackSpeed = 2.5, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 16, 
            Scale = 0.9, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.4, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[63] = {
    EnemyConfig = {
        DamageMult = 1.62, 
        HealthMult = 32.3
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 6, 
            Damage = 6, 
            Scale = 0.8, 
            WalkSpeed = 13, 
            AttackCooldown = 3, 
            AttackSpeed = 1.3, 
            AttackRange = 17, 
            AggroRange = 18, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 10, 
            AttackCooldown = 4, 
            AttackSpeed = 0.8, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[64] = {
    EnemyConfig = {
        DamageMult = 1.63, 
        HealthMult = 32.67
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 3, 
            Damage = 12, 
            Scale = 0.85, 
            WalkSpeed = 9.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.15, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.2, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.7, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[65] = {
    EnemyConfig = {
        DamageMult = 1.64, 
        HealthMult = 33.19
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.3, 1.9), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 3, 
            Damage = 11, 
            Scale = 0.85, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[66] = {
    EnemyConfig = {
        DamageMult = 1.65, 
        HealthMult = 33.85
    }, 
    Enemies = {
        {
            Name = "LippCervas", 
            Amount = 2, 
            Damage = 8, 
            Scale = 0.9, 
            WalkSpeed = 6, 
            AttackCooldown = 1, 
            AttackSpeed = 3.5, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 1, 
            Damage = 17, 
            Scale = 1.3, 
            WalkSpeed = 6, 
            AttackCooldown = 3, 
            AttackSpeed = 0.85, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 3, 
            Damage = 5, 
            Scale = 1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[67] = {
    EnemyConfig = {
        DamageMult = 1.66, 
        HealthMult = 34.67
    }, 
    Enemies = {
        {
            Name = "KarateAssassin", 
            Amount = 8, 
            Damage = 6, 
            Scale = 0.75, 
            WalkSpeed = 24, 
            AttackCooldown = 2, 
            AttackSpeed = 2.8, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.1, 0.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[68] = {
    EnemyConfig = {
        DamageMult = 1.67, 
        HealthMult = 35.63
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.9, 1.4), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 3, 
            Damage = 12, 
            Scale = 0.85, 
            WalkSpeed = 14, 
            AttackCooldown = 4, 
            AttackSpeed = 1.2, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.4), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[69] = {
    EnemyConfig = {
        DamageMult = 1.68, 
        HealthMult = 36.74
    }, 
    Enemies = {
        {
            Name = "LippCervas", 
            Amount = 1, 
            Damage = 8, 
            Scale = 1.35, 
            WalkSpeed = 3.5, 
            AttackCooldown = 1, 
            AttackSpeed = 2.5, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 3, 
            Damage = 10, 
            Scale = 0.9, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 2.1, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1.1, 
            WalkSpeed = 10.5, 
            AttackCooldown = 2, 
            AttackSpeed = 1.2, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[70] = {
    EnemyConfig = {
        DamageMult = 1.69, 
        HealthMult = 38
    }, 
    Enemies = {
        {
            Name = "Rrarrg", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 10, 
            Scale = 2.2, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 4, 
            AttackSpeed = 1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.5, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 1, 
            Damage = 17, 
            Scale = 1.5, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[71] = {
    EnemyConfig = {
        DamageMult = 1.7, 
        HealthMult = 38
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 3, 
            Damage = 6, 
            Scale = 1.2, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 2, 
            Damage = 5, 
            Scale = 1.25, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1.6, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.8, 1.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 3, 
            Damage = 6, 
            Scale = 0.9, 
            WalkSpeed = 17, 
            AttackCooldown = 2, 
            AttackSpeed = 2.2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[72] = {
    EnemyConfig = {
        DamageMult = 1.71, 
        HealthMult = 38.15
    }, 
    Enemies = {
        {
            Name = "Rrarrg", 
            Amount = 1, 
            Damage = 10, 
            Scale = 0.9, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 2.2, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "LippCervas", 
            Amount = 2, 
            Damage = 8, 
            Scale = 1, 
            WalkSpeed = 5, 
            AttackCooldown = 1, 
            AttackSpeed = 3, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[73] = {
    EnemyConfig = {
        DamageMult = 1.72, 
        HealthMult = 38.59
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 3, 
            Damage = 16, 
            Scale = 0.85, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.3, 0.7), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.1, 
            WalkSpeed = 7.5, 
            AttackCooldown = 3, 
            AttackSpeed = 0.95, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[74] = {
    EnemyConfig = {
        DamageMult = 1.73, 
        HealthMult = 39.33
    }, 
    Enemies = {
        {
            Name = "TheTickler", 
            Amount = 4, 
            Damage = 12, 
            Scale = 0.8, 
            WalkSpeed = 15, 
            AttackCooldown = 4, 
            AttackSpeed = 1.3, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1.25, 
            WalkSpeed = 9.5, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.8, 1.3), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[75] = {
    EnemyConfig = {
        DamageMult = 1.74, 
        HealthMult = 40.37
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 2, 
            AttackSpeed = 0.7, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 5, 
            Damage = 5, 
            Scale = 0.8, 
            WalkSpeed = 10, 
            AttackCooldown = 3, 
            AttackSpeed = 2.4, 
            AttackRange = 14, 
            AggroRange = 11, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[76] = {
    EnemyConfig = {
        DamageMult = 1.75, 
        HealthMult = 41.7
    }, 
    Enemies = {
        {
            Name = "Rrarrg", 
            Amount = 2, 
            Damage = 10, 
            Scale = 0.85, 
            WalkSpeed = 9.5, 
            AttackCooldown = 3, 
            AttackSpeed = 2.3, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "LippCervas", 
            Amount = 1, 
            Damage = 8, 
            Scale = 1.2, 
            WalkSpeed = 4, 
            AttackCooldown = 1, 
            AttackSpeed = 2.7, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.9, 1.4), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.1, 
            WalkSpeed = 11.5, 
            AttackCooldown = 2, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.4, 0.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[77] = {
    EnemyConfig = {
        DamageMult = 1.76, 
        HealthMult = 43.33
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1.35, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.7, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 5, 
            Damage = 6, 
            Scale = 0.85, 
            WalkSpeed = 18, 
            AttackCooldown = 2, 
            AttackSpeed = 2.3, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[78] = {
    EnemyConfig = {
        DamageMult = 1.77, 
        HealthMult = 45.26
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 17, 
            Scale = 1.2, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 3, 
            Damage = 12, 
            Scale = 0.9, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 1.1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[79] = {
    EnemyConfig = {
        DamageMult = 1.78, 
        HealthMult = 47.48
    }, 
    Enemies = {
        {
            Name = "Rrarrg", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.25, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1.7, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "LippCervas", 
            Amount = 2, 
            Damage = 8, 
            Scale = 0.85, 
            WalkSpeed = 6, 
            AttackCooldown = 1, 
            AttackSpeed = 3.5, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.2, 0.4), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1, 
            WalkSpeed = 12, 
            AttackCooldown = 4, 
            AttackSpeed = 1, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.3, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[80] = {
    EnemyConfig = {
        DamageMult = 1.79, 
        HealthMult = 50
    }, 
    Enemies = {
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 14, 
            Scale = 5.6, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.6, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.2, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.5, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 17, 
            Scale = 1.5, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[81] = {
    EnemyConfig = {
        DamageMult = 1.8, 
        HealthMult = 50
    }, 
    Enemies = {
        {
            Name = "EliteGuard", 
            Amount = 2, 
            Damage = 5, 
            Scale = 1.35, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.4, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 4, 
            Damage = 6, 
            Scale = 1, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.3, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "JellyfishDragon", 
            Amount = 2, 
            Damage = 6, 
            Scale = 1.1, 
            WalkSpeed = 9.5, 
            AttackCooldown = 3, 
            AttackSpeed = 0.95, 
            AttackRange = 17, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[82] = {
    EnemyConfig = {
        DamageMult = 1.81, 
        HealthMult = 50.23
    }, 
    Enemies = {
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            Damage = 14, 
            Scale = 2, 
            WalkSpeed = 6, 
            AttackCooldown = 3, 
            AttackSpeed = 1.5, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "Rrarrg", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[83] = {
    EnemyConfig = {
        DamageMult = 1.82, 
        HealthMult = 50.94
    }, 
    Enemies = {
        {
            Name = "LippCervas", 
            Amount = 3, 
            Damage = 8, 
            Scale = 0.8, 
            WalkSpeed = 7, 
            AttackCooldown = 1, 
            AttackSpeed = 3.8, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 1, 
            Damage = 16, 
            Scale = 1.35, 
            WalkSpeed = 6, 
            AttackCooldown = 3, 
            AttackSpeed = 0.8, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1.5, 2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[84] = {
    EnemyConfig = {
        DamageMult = 1.83, 
        HealthMult = 52.11
    }, 
    Enemies = {
        {
            Name = "SquidasaurusRex", 
            Amount = 4, 
            Damage = 12, 
            Scale = 0.85, 
            WalkSpeed = 9.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.15, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 11, 
            AttackCooldown = 4, 
            AttackSpeed = 0.9, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[85] = {
    EnemyConfig = {
        DamageMult = 1.84, 
        HealthMult = 53.75
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.35, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 4, 
            Damage = 11, 
            Scale = 0.85, 
            WalkSpeed = 13, 
            AttackCooldown = 2, 
            AttackSpeed = 1.5, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[86] = {
    EnemyConfig = {
        DamageMult = 1.85, 
        HealthMult = 55.86
    }, 
    Enemies = {
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            Damage = 14, 
            Scale = 1.8, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.7, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "Rrarrg", 
            Amount = 2, 
            Damage = 10, 
            Scale = 0.9, 
            WalkSpeed = 9, 
            AttackCooldown = 3, 
            AttackSpeed = 2.2, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[87] = {
    EnemyConfig = {
        DamageMult = 1.86, 
        HealthMult = 58.44
    }, 
    Enemies = {
        {
            Name = "KarateBruiser", 
            Amount = 5, 
            Damage = 9, 
            Scale = 0.75, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.4, 
            AttackRange = 14, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 1, 
            Damage = 5, 
            Scale = 1.35, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.4, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[88] = {
    EnemyConfig = {
        DamageMult = 1.87, 
        HealthMult = 61.49
    }, 
    Enemies = {
        {
            Name = "LippCervas", 
            Amount = 2, 
            Damage = 8, 
            Scale = 1.1, 
            WalkSpeed = 4.5, 
            AttackCooldown = 1, 
            AttackSpeed = 2.8, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 16, 
            Scale = 1, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.25, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.85, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[89] = {
    EnemyConfig = {
        DamageMult = 1.88, 
        HealthMult = 65.01
    }, 
    Enemies = {
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            Damage = 14, 
            Scale = 1.5, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.8, 1.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "Rrarrg", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.2, 
            WalkSpeed = 7.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 0.95, 
            WalkSpeed = 13, 
            AttackCooldown = 4, 
            AttackSpeed = 1.05, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.3, 0.6), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 10, 
            AttackCooldown = 2, 
            AttackSpeed = 1.1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.7, 1.2), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[90] = {
    EnemyConfig = {
        DamageMult = 1.89, 
        HealthMult = 69
    }, 
    Enemies = {
        {
            Name = "FilthyPhil", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 12, 
            Scale = 2.8, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 2, 
            Damage = 11, 
            Scale = 1, 
            WalkSpeed = 11, 
            AttackCooldown = 2, 
            AttackSpeed = 1.3, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 17, 
            Scale = 1.5, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "LippCervas", 
            Amount = 2, 
            Damage = 8, 
            Scale = 1.3, 
            WalkSpeed = 4, 
            AttackCooldown = 1, 
            AttackSpeed = 3, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[91] = {
    EnemyConfig = {
        DamageMult = 1.9, 
        HealthMult = 69
    }, 
    Enemies = {
        {
            Name = "JellyfishDragon", 
            Amount = 6, 
            Damage = 6, 
            Scale = 0.75, 
            WalkSpeed = 14, 
            AttackCooldown = 3, 
            AttackSpeed = 1.4, 
            AttackRange = 17, 
            AggroRange = 18, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "EliteGuard", 
            Amount = 1, 
            Damage = 5, 
            Scale = 1.35, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.4, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(1.3, 1.9), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[92] = {
    EnemyConfig = {
        DamageMult = 1.91, 
        HealthMult = 69.75
    }, 
    Enemies = {
        {
            Name = "FilthyPhil", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2.2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.4, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            Damage = 14, 
            Scale = 1.35, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2.1, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[93] = {
    EnemyConfig = {
        DamageMult = 1.92, 
        HealthMult = 72.01
    }, 
    Enemies = {
        {
            Name = "Rrarrg", 
            Amount = 3, 
            Damage = 10, 
            Scale = 0.85, 
            WalkSpeed = 9.5, 
            AttackCooldown = 3, 
            AttackSpeed = 2.3, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.2, 0.4), 
            AggroRangeMult = 1
        }, 
        {
            Name = "LippCervas", 
            Amount = 1, 
            Damage = 8, 
            Scale = 1.25, 
            WalkSpeed = 3.5, 
            AttackCooldown = 1, 
            AttackSpeed = 2.6, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(1.2, 1.8), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[94] = {
    EnemyConfig = {
        DamageMult = 1.93, 
        HealthMult = 75.78
    }, 
    Enemies = {
        {
            Name = "HibernationSandy", 
            Amount = 4, 
            Damage = 16, 
            Scale = 0.8, 
            WalkSpeed = 8.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.15, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.2, 0.4), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.9, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.9, 1.4), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[95] = {
    EnemyConfig = {
        DamageMult = 1.94, 
        HealthMult = 81.05
    }, 
    Enemies = {
        {
            Name = "KarateAssassin", 
            Amount = 10, 
            Damage = 6, 
            Scale = 0.75, 
            WalkSpeed = 26, 
            AttackCooldown = 2, 
            AttackSpeed = 3, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.05, 0.15), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[96] = {
    EnemyConfig = {
        DamageMult = 1.95, 
        HealthMult = 87.83
    }, 
    Enemies = {
        {
            Name = "FilthyPhil", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.25, 
            WalkSpeed = 6.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.8, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(1, 1.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            Damage = 14, 
            Scale = 1.5, 
            WalkSpeed = 7.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.9, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.8, 1.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheTickler", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1.1, 
            WalkSpeed = 11, 
            AttackCooldown = 4, 
            AttackSpeed = 0.95, 
            AttackRange = 20, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[97] = {
    EnemyConfig = {
        DamageMult = 1.96, 
        HealthMult = 96.11
    }, 
    Enemies = {
        {
            Name = "TattletaleStrangler", 
            Amount = 5, 
            Damage = 9, 
            Scale = 0.8, 
            WalkSpeed = 15, 
            AttackCooldown = 2, 
            AttackSpeed = 2.4, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.1, 0.3), 
            AggroRangeMult = 1
        }, 
        {
            Name = "BreakfastMonster", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.35, 
            WalkSpeed = 9, 
            AttackCooldown = 2, 
            AttackSpeed = 1, 
            AttackRange = 28, 
            AggroRange = 16, 
            Delay = NumberRange.new(1.3, 1.9), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[98] = {
    EnemyConfig = {
        DamageMult = 1.97, 
        HealthMult = 105.9
    }, 
    Enemies = {
        {
            Name = "Rrarrg", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.15, 
            WalkSpeed = 7.5, 
            AttackCooldown = 3, 
            AttackSpeed = 1.9, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "LippCervas", 
            Amount = 3, 
            Damage = 8, 
            Scale = 0.85, 
            WalkSpeed = 6, 
            AttackCooldown = 1, 
            AttackSpeed = 3.5, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.2, 0.4), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[99] = {
    EnemyConfig = {
        DamageMult = 1.98, 
        HealthMult = 117.2
    }, 
    Enemies = {
        {
            Name = "FilthyPhil", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TheAppetizer", 
            Amount = 1, 
            Damage = 14, 
            Scale = 1.2, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2.1, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.4, 0.8), 
            AggroRangeMult = 1
        }, 
        {
            Name = "HibernationSandy", 
            Amount = 2, 
            Damage = 16, 
            Scale = 1.1, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 0.95, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.6, 1.1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 2, 
            Damage = 12, 
            Scale = 1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
v0.FloorConfigs[100] = {
    EnemyConfig = {
        DamageMult = 2, 
        HealthMult = 130
    }, 
    Enemies = {
        {
            Name = "MasterUdon", 
            Amount = 1, 
            IsBoss = true, 
            Damage = 16, 
            Scale = 4, 
            WalkSpeed = 7, 
            AttackCooldown = 3, 
            AttackSpeed = 1.5, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "KarateAssassin", 
            Amount = 6, 
            Damage = 6, 
            Scale = 0.85, 
            WalkSpeed = 18, 
            AttackCooldown = 2, 
            AttackSpeed = 2.3, 
            AttackRange = 20, 
            AggroRange = 30, 
            Delay = NumberRange.new(0.2, 0.5), 
            AggroRangeMult = 1
        }, 
        {
            Name = "TattletaleStrangler", 
            Amount = 2, 
            Damage = 10, 
            Scale = 1.2, 
            WalkSpeed = 12, 
            AttackCooldown = 2, 
            AttackSpeed = 1.8, 
            AttackRange = 14, 
            AggroRange = 12, 
            Delay = NumberRange.new(0.4, 1), 
            AggroRangeMult = 1
        }, 
        {
            Name = "SquidasaurusRex", 
            Amount = 1, 
            Damage = 12, 
            Scale = 1.2, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 1, 
            AttackRange = 14, 
            AggroRange = 10, 
            Delay = NumberRange.new(0.8, 1.2), 
            AggroRangeMult = 1
        }, 
        {
            Name = "Rrarrg", 
            Amount = 1, 
            Damage = 10, 
            Scale = 1.1, 
            WalkSpeed = 8, 
            AttackCooldown = 3, 
            AttackSpeed = 2, 
            AttackRange = 14, 
            AggroRange = 20, 
            Delay = NumberRange.new(0.5, 1), 
            AggroRangeMult = 1
        }
    }
};
return v0;