return {
    [1] = {
        type = "Currency", 
        name = "Gems", 
        amount = 100
    }, 
    [2] = {
        type = "Currency", 
        name = "Coins", 
        amount = 250
    }, 
    [3] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 3
    }, 
    [4] = {
        type = "Inventory", 
        name = "Aged Patty", 
        amount = 10
    }, 
    [5] = {
        type = "Inventory", 
        name = "TreasureChest", 
        amount = 5
    }, 
    [6] = {
        type = "Currency", 
        name = "Gems", 
        amount = 200
    }, 
    [7] = {
        type = "Currency", 
        name = "Coins", 
        amount = 500
    }, 
    [8] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 5
    }, 
    [9] = {
        type = "Inventory", 
        name = "Aged Patty", 
        amount = 25
    }, 
    [10] = {
        type = "Inventory", 
        name = "TreasureChest", 
        amount = 10
    }, 
    [11] = {
        type = "Currency", 
        name = "Gems", 
        amount = 300
    }, 
    [12] = {
        type = "Currency", 
        name = "Coins", 
        amount = 750
    }, 
    [13] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 10
    }, 
    [14] = {
        type = "Inventory", 
        name = "Aged Patty", 
        amount = 50
    }, 
    [15] = {
        type = "Inventory", 
        name = "TreasureChest", 
        amount = 15
    }, 
    [16] = {
        type = "Currency", 
        name = "Gems", 
        amount = 500
    }, 
    [17] = {
        type = "Currency", 
        name = "Coins", 
        amount = 1000
    }, 
    [18] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 15
    }, 
    [19] = {
        type = "Inventory", 
        name = "JellyPatty", 
        amount = 15
    }, 
    [20] = {
        type = "Inventory", 
        name = "EpicTreasureChest", 
        amount = 5
    }, 
    [21] = {
        type = "Currency", 
        name = "Gems", 
        amount = 750
    }, 
    [22] = {
        type = "Currency", 
        name = "Coins", 
        amount = 1500
    }, 
    [23] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 20
    }, 
    [24] = {
        type = "Inventory", 
        name = "JellyPatty", 
        amount = 25
    }, 
    [25] = {
        type = "Inventory", 
        name = "EpicTreasureChest", 
        amount = 10
    }, 
    [26] = {
        type = "Currency", 
        name = "Gems", 
        amount = 1000
    }, 
    [27] = {
        type = "Currency", 
        name = "Coins", 
        amount = 2000
    }, 
    [28] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 25
    }, 
    [29] = {
        type = "Inventory", 
        name = "JellyPatty", 
        amount = 50
    }, 
    [30] = {
        type = "Inventory", 
        name = "EpicTreasureChest", 
        amount = 15
    }, 
    [31] = {
        type = "Currency", 
        name = "Gems", 
        amount = 1250
    }, 
    [32] = {
        type = "Currency", 
        name = "Coins", 
        amount = 2500
    }, 
    [33] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 30
    }, 
    [34] = {
        type = "Inventory", 
        name = "Pretty Patties", 
        amount = 15
    }, 
    [35] = {
        type = "Inventory", 
        name = "LegendaryTreasureChest", 
        amount = 3
    }, 
    [36] = {
        type = "Currency", 
        name = "Gems", 
        amount = 1500
    }, 
    [37] = {
        type = "Currency", 
        name = "Coins", 
        amount = 3000
    }, 
    [38] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 35
    }, 
    [39] = {
        type = "Inventory", 
        name = "Pretty Patties", 
        amount = 25
    }, 
    [40] = {
        type = "Inventory", 
        name = "LegendaryTreasureChest", 
        amount = 5
    }, 
    [41] = {
        type = "Currency", 
        name = "Gems", 
        amount = 2000
    }, 
    [42] = {
        type = "Currency", 
        name = "Coins", 
        amount = 4000
    }, 
    [43] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 40
    }, 
    [44] = {
        type = "Inventory", 
        name = "Pretty Patties", 
        amount = 50
    }, 
    [45] = {
        type = "Inventory", 
        name = "LegendaryTreasureChest", 
        amount = 10
    }, 
    [46] = {
        type = "Currency", 
        name = "Gems", 
        amount = 2500
    }, 
    [47] = {
        type = "Currency", 
        name = "Coins", 
        amount = 5000
    }, 
    [48] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 50
    }, 
    [49] = {
        type = "Inventory", 
        name = "Pretty Patties", 
        amount = 100
    }, 
    [50] = {
        type = "Unit", 
        name = "BrokenSquidward", 
        extraData = {}, 
        _isMaxLevel = true
    }, 
    [51] = {
        type = "Unit", 
        name = "BrokenSquidward", 
        extraData = {
            Shiny = true
        }
    }, 
    [52] = {
        type = "Unit", 
        name = "BrokenSquidward", 
        extraData = {
            Wumbo = true
        }
    }, 
    [53] = {
        type = "Unit", 
        name = "BrokenSquidward", 
        extraData = {
            Shiny = true, 
            Wumbo = true
        }
    }, 
    [54] = {
        type = "Unit", 
        name = "BrokenSquidward", 
        extraData = {}
    }
};