return {
    [1] = {
        type = "Currency", 
        name = "Gems", 
        amount = 25
    }, 
    [2] = {
        type = "Currency", 
        name = "Coins", 
        amount = 50
    }, 
    [3] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [4] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 3
    }, 
    [5] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 1
    }, 
    [6] = {
        type = "Currency", 
        name = "Gems", 
        amount = 50
    }, 
    [7] = {
        type = "Currency", 
        name = "Coins", 
        amount = 100
    }, 
    [8] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [9] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 5
    }, 
    [10] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [11] = {
        type = "Currency", 
        name = "Gems", 
        amount = 100
    }, 
    [12] = {
        type = "Currency", 
        name = "Coins", 
        amount = 150
    }, 
    [13] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [14] = {
        type = "Inventory", 
        name = "Kelp Shake", 
        amount = 3
    }, 
    [15] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 2
    }, 
    [16] = {
        type = "Currency", 
        name = "Gems", 
        amount = 150
    }, 
    [17] = {
        type = "Currency", 
        name = "Coins", 
        amount = 200
    }, 
    [18] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [19] = {
        type = "Inventory", 
        name = "Kelp Shake", 
        amount = 5
    }, 
    [20] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [21] = {
        type = "Currency", 
        name = "Gems", 
        amount = 200
    }, 
    [22] = {
        type = "Currency", 
        name = "Coins", 
        amount = 250
    }, 
    [23] = {
        type = "Inventory", 
        name = "COINS_60", 
        amount = 1
    }, 
    [24] = {
        type = "Inventory", 
        name = "Krabby Patty", 
        amount = 3
    }, 
    [25] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 3
    }, 
    [26] = {
        type = "Currency", 
        name = "Gems", 
        amount = 250
    }, 
    [27] = {
        type = "Currency", 
        name = "Coins", 
        amount = 300
    }, 
    [28] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [29] = {
        type = "Inventory", 
        name = "Krabby Patty", 
        amount = 5
    }, 
    [30] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [31] = {
        type = "Currency", 
        name = "Gems", 
        amount = 300
    }, 
    [32] = {
        type = "Currency", 
        name = "Coins", 
        amount = 350
    }, 
    [33] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [34] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 8
    }, 
    [35] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 5
    }, 
    [36] = {
        type = "Currency", 
        name = "Gems", 
        amount = 350
    }, 
    [37] = {
        type = "Currency", 
        name = "Coins", 
        amount = 400
    }, 
    [38] = {
        type = "Inventory", 
        name = "COINS_60", 
        amount = 1
    }, 
    [39] = {
        type = "Inventory", 
        name = "Kelp Shake", 
        amount = 8
    }, 
    [40] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [41] = {
        type = "Currency", 
        name = "Gems", 
        amount = 400
    }, 
    [42] = {
        type = "Currency", 
        name = "Coins", 
        amount = 450
    }, 
    [43] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [44] = {
        type = "Inventory", 
        name = "Krabby Patty", 
        amount = 8
    }, 
    [45] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 5
    }, 
    [46] = {
        type = "Currency", 
        name = "Gems", 
        amount = 500
    }, 
    [47] = {
        type = "Currency", 
        name = "Coins", 
        amount = 750
    }, 
    [48] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [49] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 12
    }, 
    [50] = {
        type = "Unit", 
        name = "RandomEpicWumbo", 
        amount = 1
    }
};