local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = game:GetService("RunService");
local _ = require(l_ReplicatedStorage_0.Shared.Data.Purchases);
return {
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 1000
        }, 
        purchaseName = "GemProgressionPack1"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 2000
        }, 
        purchaseName = "GemProgressionPack2"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 5000
        }, 
        purchaseName = "GemProgressionPack3"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 10000
        }, 
        purchaseName = "GemProgressionPack4"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 25000
        }, 
        purchaseName = "GemProgressionPack5"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 50000
        }, 
        purchaseName = "GemProgressionPack6"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 100000
        }, 
        purchaseName = "GemProgressionPack7"
    }
};