return {
    RaritiesPool = {
        Rare = {
            weight = 64
        }, 
        Epic = {
            weight = 20
        }, 
        Legendary = {
            weight = 10
        }, 
        Mythic = {
            weight = 5
        }, 
        Secret = {
            weight = 1
        }
    }, 
    LootPool = {
        Rare = {
            {
                type = "Unit", 
                name = "MegaHydraKaren", 
                extraData = {}, 
                amount = 1, 
                weight = 64
            }
        }, 
        Epic = {
            {
                type = "Unit", 
                name = "MegaHydraKaren", 
                extraData = {
                    Shiny = true
                }, 
                amount = 1, 
                weight = 20
            }
        }, 
        Legendary = {
            {
                type = "Unit", 
                name = "MegaHydraKaren", 
                extraData = {
                    Wumbo = true
                }, 
                amount = 1, 
                weight = 10
            }
        }, 
        Mythic = {
            {
                type = "Unit", 
                name = "MegaHydraKaren", 
                extraData = {
                    Shiny = true, 
                    Wumbo = true
                }, 
                amount = 1, 
                weight = 5
            }
        }, 
        Secret = {
            {
                type = "Unit", 
                name = "MegaHydraKaren", 
                extraData = {
                    Shiny = true, 
                    Wumbo = true, 
                    Stars = 5, 
                    Level = 100, 
                    Trait = {
                        Name = "Strike", 
                        Tier = 1
                    }, 
                    Trait2 = {
                        Name = "Reach", 
                        Tier = 1
                    }
                }, 
                amount = 1, 
                weight = 1
            }
        }
    }
};