return {
    _resetType = "Weekly"; 
    {
        Name = "Endless1", 
        DisplayName = "Endless I", 
        Description = "Clear 50 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 50, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 250
            }, 
            {
                type = "Experience", 
                amount = 250
            }, 
            {
                type = "Currency", 
                name = "Coins", 
                amount = 1000
            }
        }
    }, 
    {
        Name = "Endless2", 
        DisplayName = "Endless II", 
        Description = "Clear 100 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 100, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 350
            }, 
            {
                type = "Experience", 
                amount = 350
            }, 
            {
                type = "Currency", 
                name = "Gems", 
                amount = 250
            }
        }
    }, 
    {
        Name = "Endless3", 
        DisplayName = "Endless III", 
        Description = "Clear 250 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 250, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 500
            }, 
            {
                type = "Experience", 
                amount = 500
            }, 
            {
                type = "Inventory", 
                name = "TreasureChest", 
                amount = 5
            }
        }
    }, 
    {
        Name = "Endless4", 
        DisplayName = "Endless IV", 
        Description = "Clear 500 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 500, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 750
            }, 
            {
                type = "Experience", 
                amount = 750
            }, 
            {
                type = "Inventory", 
                name = "EpicTreasureChest", 
                amount = 10
            }
        }
    }, 
    {
        Name = "Endless5", 
        DisplayName = "Endless V", 
        Description = "Clear 1,000 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 1000, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 1000
            }, 
            {
                type = "Experience", 
                amount = 1000
            }, 
            {
                type = "Inventory", 
                name = "EpicTreasureChest", 
                amount = 15
            }
        }
    }, 
    {
        Name = "Endless6", 
        DisplayName = "Endless VI", 
        Description = "Clear 2,500 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 2500, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 2500
            }, 
            {
                type = "Experience", 
                amount = 2500
            }, 
            {
                type = "Inventory", 
                name = "LegendaryTreasureChest", 
                amount = 15
            }
        }
    }, 
    {
        Name = "Endless7", 
        DisplayName = "Endless VII", 
        Description = "Clear 5,000 Waves (Any Endless)", 
        Type = "ClearWavesEndless", 
        RequiredValue = 5000, 
        Rewards = {
            {
                type = "SeasonXP", 
                name = "SeasonXP", 
                amount = 5000
            }, 
            {
                type = "Experience", 
                amount = 5000
            }, 
            {
                type = "Inventory", 
                name = "MythicTreasureChest", 
                amount = 25
            }
        }
    }
};