return {
    _order = 2, 
    _displayName = "Jellyfish Fields", 
    FullCompletionRewards = {
        {
            type = "Currency", 
            name = "MagicConch", 
            amount = 1
        }
    }; 
    {
        Name = "NormalMaster", 
        DisplayName = "100% Normal Difficulty", 
        Description = "Clear All Chapters of Jellyfish Fields on Normal Difficulty", 
        Type = "AllChaptersNormal", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Inventory", 
                name = "COINS_60", 
                amount = 1
            }
        }
    }, 
    {
        Name = "HardMaster", 
        DisplayName = "100% Hard Difficulty", 
        Description = "Clear All Chapters of Jellyfish Fields on Hard Difficulty", 
        Type = "AllChaptersHard", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Inventory", 
                name = "GEMS_60", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare1", 
        DisplayName = "Nightmare Clear I", 
        Description = "Clear Chapter 1 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter1", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare2", 
        DisplayName = "Nightmare Clear II", 
        Description = "Clear Chapter 2 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter2", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare3", 
        DisplayName = "Nightmare Clear III", 
        Description = "Clear Chapter 3 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter3", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare4", 
        DisplayName = "Nightmare Clear IV", 
        Description = "Clear Chapter 4 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter4", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare5", 
        DisplayName = "Nightmare Clear V", 
        Description = "Clear Chapter 5 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter5", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare6", 
        DisplayName = "Nightmare Clear VI", 
        Description = "Clear Chapter 6 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter6", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare7", 
        DisplayName = "Nightmare Clear VII", 
        Description = "Clear Chapter 7 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter7", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare8", 
        DisplayName = "Nightmare Clear VIII", 
        Description = "Clear Chapter 8 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter8", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare9", 
        DisplayName = "Nightmare Clear IX", 
        Description = "Clear Chapter 9 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter9", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }, 
    {
        Name = "Nightmare10", 
        DisplayName = "Nightmare Clear X", 
        Description = "Clear Chapter 10 of Jellyfish Fields on Nightmare Difficulty", 
        Type = "NightmareWinChapter10", 
        RequiredValue = 1, 
        Rewards = {
            {
                type = "Currency", 
                name = "TraitRolls", 
                amount = 1
            }
        }
    }
};