return {
    General = {
        Factions = {
            background = "rbxassetid://82208886331151", 
            destination = "FACTION GROUNDS", 
            backgroundColor = Color3.new(1, 1, 1), 
            hint = "Home to band geeks, jellyfishers, and partygoers alike"
        }, 
        Trading = {
            background = "rbxassetid://74986310361814", 
            destination = "TRADING HUB", 
            backgroundColor = Color3.new(1, 1, 1), 
            hint = "A spooky, trading vessel of the Flying Dutchman"
        }, 
        Cave = {
            background = "rbxassetid://110182161074577", 
            destination = "U\224\184\160\207\130\209\146\224\184\132\208\179t\209\148\224\185\148 \207\130\224\184\132\215\169\209\148", 
            backgroundColor = Color3.new(1, 1, 1), 
            hint = "\224\184\132 \224\185\148\209\148\209\148\215\167 \207\130\209\146\224\184\132\224\184\163\224\185\147 \224\184\172\209\146\209\148\208\179\209\148 \224\184\132\224\184\160\207\130\224\185\128\209\148\224\184\160t \224\184\163\209\148\207\130\208\179\209\148t\224\184\163 \201\173\224\185\128\209\148 \224\184\162\224\184\160\224\185\148\224\185\128\224\184\163t\224\184\162\208\179\224\185\146\209\148\224\185\148"
        }, 
        Lobby = {
            background = "rbxassetid://86049446236203", 
            destination = "THE REEF RETREAT", 
            backgroundColor = Color3.new(1, 1, 1), 
            hint = "A vibrant coral reef bustling with life and color"
        }, 
        AFK = {
            background = "rbxassetid://119272627462285", 
            destination = "AFK ROCK", 
            backgroundColor = Color3.new(1, 1, 1), 
            hint = "Patrick's laid-back underground home beneath a rock"
        }, 
        KarateLobby = {
            background = "rbxassetid://96106700714450", 
            destination = "KARATE ISLAND", 
            backgroundColor = Color3.new(1, 1, 1), 
            hint = "A remote island ruled by karate masters"
        }
    }, 
    Game = {
        Coliseum = {
            {
                background = "rbxassetid://94472561950900", 
                destination = "CHUM COLISEUM", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Where epic fights unfold beneath a cheering crowd"
            }
        }, 
        FlyingDutchmanShip = {
            {
                background = "rbxassetid://135676182957952", 
                destination = "FLYING DUTCHMAN SHIP", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A cursed vessel bound to the abyss"
            }
        }, 
        GooLagoon = {
            {
                background = "rbxassetid://137817308510733", 
                destination = "GOO LAGOON", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A stinky mud puddle, now Bikini Bottom\226\128\153s beach hotspot"
            }
        }, 
        ConchStreetSnow = {
            {
                background = "rbxassetid://123259314333134", 
                destination = "CONCH STREET", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Home to Bikini Bottom's most notable residents"
            }
        }, 
        JellyfishFields = {
            {
                background = "rbxassetid://122438464352057", 
                destination = "JELLYFISH FIELDS", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A meadow alive with jellyfish and jellyfishing fun"
            }, 
            {
                background = "rbxassetid://139798482825117", 
                destination = "JELLYFISH FIELDS", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A meadow alive with jellyfish and jellyfishing fun"
            }
        }, 
        ChumBucket = {
            {
                background = "rbxassetid://76023102359620", 
                destination = "CHUM BUCKET", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A sinister diner and laboratory with schemes aplenty"
            }, 
            {
                background = "rbxassetid://133462440281015", 
                destination = "CHUM BUCKET", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A sinister diner and laboratory with schemes aplenty"
            }
        }, 
        KrustyKrab = {
            {
                background = "rbxassetid://83832095895440", 
                destination = "KRUSTY KRAB", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "The iconic eatery known for it's Krabby Patties"
            }, 
            {
                background = "rbxassetid://139444023869294", 
                destination = "KRUSTY KRAB", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "The iconic eatery known for it's Krabby Patties"
            }
        }, 
        MiddleAges = {
            {
                background = "rbxassetid://116328874266301", 
                destination = "MIDDLE AGES", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Where ancient kingdoms battled and legends rose"
            }
        }, 
        BubbleBowl = {
            {
                background = "rbxassetid://121849741763115", 
                destination = "BUBBLE BOWL", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "The legendary stage where tunes and talent collide"
            }
        }, 
        BikiniBottom = {
            {
                background = "rbxassetid://128214680337953", 
                destination = "BIKINI BOTTOM", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A deep-sea city bursting with life, laughs, and surprises"
            }
        }, 
        BoatingSchool = {
            {
                background = "rbxassetid://128016007819609", 
                destination = "MRS. PUFF'S BOATING SCHOOL", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Training grounds for future boat drivers"
            }
        }, 
        RockBottom = {
            {
                background = "rbxassetid://93686984590604", 
                destination = "ROCK BOTTOM", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A dim, eerie place at the ocean\226\128\153s edge"
            }, 
            {
                background = "rbxassetid://137782176375968", 
                destination = "ROCK BOTTOM", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A dim, eerie place at the ocean\226\128\153s edge"
            }
        }, 
        ConchStreet = {
            {
                background = "rbxassetid://109981724094408", 
                destination = "CONCH STREET", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Home to Bikini Bottom's most notable residents"
            }, 
            {
                background = "rbxassetid://83446676447011", 
                destination = "CONCH STREET", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Home to Bikini Bottom's most notable residents"
            }
        }, 
        SandysTreedome = {
            {
                background = "rbxassetid://103653387512856", 
                destination = "SANDY'S TREEDOME", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A cozy, air-filled paradise in the deep sea"
            }, 
            {
                background = "rbxassetid://75060235077584", 
                destination = "SANDY'S TREEDOME", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A cozy, air-filled paradise in the deep sea"
            }
        }, 
        PattyVault = {
            {
                background = "rbxassetid://94139345045223", 
                destination = "PATTY VAULT", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A vault full of delectable Krabby Patties"
            }
        }, 
        Mermalair = {
            {
                background = "rbxassetid://135614508107311", 
                destination = "MERMALAIR", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "Hidden headquarters of heroics and underwater justice"
            }
        }, 
        NewKelpCity = {
            {
                background = "rbxassetid://136774363702808", 
                destination = "NEW KELP CITY", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A restless metropolis where gangs rise in the shadows"
            }, 
            {
                background = "rbxassetid://82460203676048", 
                destination = "NEW KELP CITY", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A restless metropolis where gangs rise in the shadows"
            }, 
            {
                background = "rbxassetid://123886374088405", 
                destination = "NEW KELP CITY", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A restless metropolis where gangs rise in the shadows"
            }, 
            {
                background = "rbxassetid://115111652434664", 
                destination = "NEW KELP CITY", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A restless metropolis where gangs rise in the shadows"
            }
        }, 
        KampKoral = {
            {
                background = "rbxassetid://110396651144615", 
                destination = "KAMP KORAL", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A lakefront retreat for fun, friends, and fresh air"
            }, 
            {
                background = "rbxassetid://83528866175285", 
                destination = "KAMP KORAL", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A lakefront retreat for fun, friends, and fresh air"
            }
        }, 
        TowerOfKarate = {
            {
                background = "rbxassetid://86963161015151", 
                destination = "TOWER OF KARATE", 
                backgroundColor = Color3.new(1, 1, 1), 
                hint = "A towering test of strength, skill, and spirit"
            }
        }
    }
};