return {
    Lighting = {
        ClockTime = 9, 
        ColorShift_Bottom = Color3.fromRGB(0, 0, 0), 
        FogColor = Color3.fromRGB(192, 192, 192), 
        FogEnd = 100000, 
        FogStart = 0, 
        EnvironmentDiffuseScale = 0, 
        EnvironmentSpecularScale = 0.5, 
        ExposureCompensation = -1, 
        GeographicLatitude = 25, 
        Ambient = Color3.fromRGB(85, 85, 127), 
        OutdoorAmbient = Color3.fromRGB(238, 255, 230), 
        ShadowSoftness = 0.20000000298023224, 
        Brightness = 2.25, 
        ColorShift_Top = Color3.fromRGB(255, 228, 160), 
        GlobalShadows = true
    }, 
    Sky = {
        CelestialBodiesShown = true, 
        MoonAngularSize = 11, 
        MoonTextureId = "", 
        SkyboxBk = "rbxassetid://72437203450203", 
        SkyboxDn = "rbxassetid://130628124871858", 
        SkyboxFt = "rbxassetid://102637229636816", 
        SkyboxLf = "rbxassetid://74673930789736", 
        SkyboxRt = "rbxassetid://78340525217380", 
        SkyboxUp = "rbxassetid://127933020500072", 
        StarCount = 3000, 
        SunAngularSize = 0, 
        SunTextureId = "rbxasset://sky/sun.jpg", 
        Name = "SpongebobSky"
    }, 
    Atmosphere = {
        Density = 0.30000001192092896, 
        Offset = 0, 
        Name = "Atmosphere", 
        Color = Color3.fromRGB(0, 0, 0), 
        Decay = Color3.fromRGB(218, 196, 174), 
        Glare = 1.5, 
        Haze = 2.0999999046325684
    }, 
    PostEffects = {
        Lighting = {
            BloomEffect = {
                Name = "Bloom", 
                Enabled = true, 
                Intensity = 1, 
                Size = 56, 
                Threshold = 1.843000054359436
            }, 
            ColorCorrectionEffect = {
                Name = "ColorCorrection", 
                Brightness = 0.05000000074505806, 
                Contrast = 0.25, 
                Enabled = true, 
                Saturation = 0.20000000298023224, 
                TintColor = Color3.fromRGB(255, 255, 255)
            }, 
            SunRaysEffect = {
                Name = "SunRays", 
                Enabled = true, 
                Intensity = 0.10000000149011612, 
                Spread = 1
            }
        }, 
        Camera = {}
    }, 
    Clouds = {
        Cover = 0.8500000238418579, 
        Density = 0.03500000014901161, 
        Color = Color3.fromRGB(22, 7, 25), 
        Enabled = true
    }
};