return {
    Lighting = {
        ExposureCompensation = 0.10000000149011612, 
        ColorShift_Bottom = Color3.fromRGB(255, 230, 189), 
        FogColor = Color3.fromRGB(179, 200, 230), 
        FogEnd = 600, 
        TimeOfDay = "06:12:00", 
        EnvironmentDiffuseScale = 1, 
        EnvironmentSpecularScale = 1, 
        ClockTime = 6.199999809265137, 
        FogStart = 50, 
        Ambient = Color3.fromRGB(119, 110, 149), 
        OutdoorAmbient = Color3.fromRGB(170, 160, 189), 
        GlobalShadows = true, 
        Brightness = 1.5, 
        ColorShift_Top = Color3.fromRGB(219, 189, 255), 
        GeographicLatitude = 0
    }, 
    PostEffects = {
        SunRaysEffect = {
            Enabled = true, 
            Intensity = 0.03999999910593033, 
            Spread = 0.44999998807907104
        }, 
        Sky = {
            StarCount = 1000, 
            SkyboxUp = "rbxassetid://6412503613", 
            MoonTextureId = "rbxassetid://6444320592", 
            SkyboxBk = "rbxassetid://6444884337", 
            CelestialBodiesShown = true, 
            SkyboxDn = "rbxassetid://6444884785", 
            SkyboxLf = "rbxassetid://6444884337", 
            SunTextureId = "rbxassetid://6196665106", 
            SunAngularSize = 8, 
            SkyboxFt = "rbxassetid://6444884337", 
            SkyboxRt = "rbxassetid://6444884337", 
            MoonAngularSize = 4
        }, 
        Atmosphere = {
            Density = 0.3499999940395355, 
            Haze = 1, 
            Color = Color3.fromRGB(230, 239, 255), 
            Decay = Color3.fromRGB(189, 209, 230), 
            Glare = 1.2000000476837158, 
            Offset = 0.20000000298023224
        }, 
        ColorCorrectionEffect = {
            TintColor = Color3.fromRGB(255, 244, 235), 
            Brightness = 0.05000000074505806, 
            Saturation = -0.03999999910593033, 
            Contrast = 0.15000000596046448
        }, 
        BloomEffect = {
            Enabled = true, 
            Threshold = 1.399999976158142, 
            Intensity = 0.6000000238418579, 
            Size = 20
        }
    }, 
    Clouds = {
        Density = 0.10999999940395355, 
        Color = Color3.fromRGB(255, 211, 244), 
        Cover = 0.6499999761581421
    }
};