return {
    Standard = {
        isMythicBanner = true; 
        {
            ManRay = 3, 
            DirtyDan = 2, 
            Tiff = 1
        }, 
        {
            SmittyWerbenjagermanjensen = 2, 
            ManRay = 3, 
            Bert = 1
        }, 
        {
            RealisticFishHead = 2, 
            PinheadLarry = 1, 
            KingNeptune = 3
        }
    }, 
    Boosted = {
        isMythicBanner = true; 
        {
            ManRay = 3, 
            DirtyDan = 2, 
            Tiff = 1
        }, 
        {
            RealisticFishHead = 2, 
            PinheadLarry = 1, 
            KingNeptune = 3
        }, 
        {
            SmittyWerbenjagermanjensen = 2, 
            ManRay = 3, 
            Bert = 1
        }
    }, 
    Exclusive = {
        isMythicBanner = false, 
        HibernationSandy = 50, 
        DreamPatrick = 50, 
        Tattletale = 50
    }
};