return {
    Lighting = {
        ExposureCompensation = 0.20000000298023224, 
        ColorShift_Bottom = Color3.fromRGB(40, 40, 59), 
        FogColor = Color3.fromRGB(49, 49, 70), 
        FogEnd = 800, 
        TimeOfDay = "21:00:00", 
        EnvironmentDiffuseScale = 0.699999988079071, 
        EnvironmentSpecularScale = 0.5, 
        ClockTime = 21, 
        FogStart = 100, 
        Ambient = Color3.fromRGB(89, 89, 110), 
        OutdoorAmbient = Color3.fromRGB(100, 100, 130), 
        GlobalShadows = true, 
        Brightness = 4, 
        ColorShift_Top = Color3.fromRGB(19, 19, 49), 
        GeographicLatitude = 0
    }, 
    PostEffects = {
        SunRaysEffect = {
            Enabled = false, 
            Intensity = 0.25, 
            Spread = 1
        }, 
        Sky = {
            StarCount = 4500, 
            SkyboxUp = "rbxassetid://6412503613", 
            MoonTextureId = "rbxassetid://6444320592", 
            SkyboxBk = "rbxassetid://6444884337", 
            CelestialBodiesShown = true, 
            SkyboxDn = "rbxassetid://6444884785", 
            SkyboxLf = "rbxassetid://6444884337", 
            SunTextureId = "", 
            SunAngularSize = 0, 
            SkyboxFt = "rbxassetid://6444884337", 
            SkyboxRt = "rbxassetid://6444884337", 
            MoonAngularSize = 11
        }, 
        Atmosphere = {
            Density = 0.30000001192092896, 
            Haze = 0.30000001192092896, 
            Color = Color3.fromRGB(70, 80, 100), 
            Decay = Color3.fromRGB(59, 70, 89), 
            Glare = 0.800000011920929, 
            Offset = 0.20000000298023224
        }, 
        ColorCorrectionEffect = {
            TintColor = Color3.fromRGB(200, 219, 255), 
            Brightness = 0.05999999865889549, 
            Saturation = -0.10000000149011612, 
            Contrast = 0.15000000596046448
        }, 
        BloomEffect = {
            Enabled = true, 
            Threshold = 1.600000023841858, 
            Intensity = 0.25, 
            Size = 20
        }
    }, 
    Clouds = {
        Density = 0.15000000596046448, 
        Color = Color3.fromRGB(89, 100, 119), 
        Cover = 0.7200000286102295
    }
};