return {
    [1] = {
        required = 1, 
        objective = "Complete <rich>Christmas Conch</rich> on <rich>Davy Jones</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "ChallengeToken", 
                amount = 1000
            }, 
            {
                type = "Inventory", 
                name = "Epic_Olipop", 
                amount = 25, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 37, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [2] = {
        required = 1, 
        objective = "Complete <rich>Patty Vault</rich> on <rich>Davy Jones</rich> Difficulty.", 
        rewards = {
            {
                type = "Inventory", 
                name = "ChallengeGift", 
                amount = 10
            }, 
            {
                type = "Inventory", 
                name = "Epic_Olipop", 
                amount = 50, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 75, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [3] = {
        required = 1, 
        objective = "Complete <rich>Dutchman's Ship</rich> on <rich>Davy Jones</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "DriverLicense", 
                amount = 5000
            }, 
            {
                type = "Inventory", 
                name = "Epic_Olipop", 
                amount = 75, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 112, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [4] = {
        required = 1, 
        objective = "Complete <rich>Goo Lagoon</rich> on <rich>Davy Jones</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "MagicConch", 
                amount = 50
            }, 
            {
                type = "Inventory", 
                name = "Epic_Olipop", 
                amount = 100, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 150, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [5] = {
        required = 0, 
        rewards = {
            {
                type = "Inventory", 
                name = "OlipopRelic2", 
                amount = 1, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "LegendaryTreasureChest", 
                amount = 100
            }, 
            {
                type = "Inventory", 
                name = "BreadRelic2", 
                amount = 1, 
                useIfAdsDisabled = true
            }
        }
    }
};