return {
    [1] = {
        required = 5, 
        objective = "Complete <rich><amount> Chapters</rich> of <rich>Conch Street</rich> on <rich>Nightmare</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "Coins", 
                amount = 10000
            }, 
            {
                type = "Inventory", 
                name = "Rare_Olipop", 
                amount = 25, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 25, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [2] = {
        required = 5, 
        objective = "Complete <rich><amount> Chapters</rich> of <rich>Krusty Krab</rich> on <rich>Nightmare</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "Gems", 
                amount = 5000
            }, 
            {
                type = "Inventory", 
                name = "Rare_Olipop", 
                amount = 50, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 50, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [3] = {
        required = 5, 
        objective = "Complete <rich><amount> Chapters</rich> of <rich>Sandy's Tree Dome</rich> on <rich>Nightmare</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "GoldenTraitRolls", 
                amount = 25
            }, 
            {
                type = "Inventory", 
                name = "Rare_Olipop", 
                amount = 75, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 75, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [4] = {
        required = 1, 
        objective = "Complete <rich>Chapter 10</rich> of <rich>Rock Bottom</rich> on <rich>Nightmare</rich> Difficulty.", 
        rewards = {
            {
                type = "Currency", 
                name = "MagicConch", 
                amount = 25
            }, 
            {
                type = "Inventory", 
                name = "Rare_Olipop", 
                amount = 100, 
                isAdReward = true
            }, 
            {
                type = "Inventory", 
                name = "CannedBread", 
                amount = 100, 
                useIfAdsDisabled = true
            }
        }
    }, 
    [5] = {
        required = 0, 
        rewards = {
            {
                type = "Inventory", 
                name = "OlipopRelic1", 
                amount = 1, 
                isAdReward = true
            }, 
            {
                type = "Currency", 
                name = "MagicConch", 
                amount = 25
            }, 
            {
                type = "Inventory", 
                name = "BreadRelic1", 
                amount = 1, 
                useIfAdsDisabled = true
            }
        }
    }
};