return {
    _sheets = {
        [1] = "rbxassetid://138552731400891"
    }, 
    OlipopRelic1 = {
        index = 1, 
        sheet = 1
    }, 
    OlipopRelic2 = {
        index = 2, 
        sheet = 1
    }, 
    OlipopRelic3 = {
        index = 3, 
        sheet = 1
    }, 
    OlipopRelic4 = {
        index = 4, 
        sheet = 1
    }, 
    OlipopRelic5 = {
        index = 5, 
        sheet = 1
    }, 
    Epic_Olipop = {
        index = 6, 
        sheet = 1
    }, 
    Legendary_Olipop = {
        index = 7, 
        sheet = 1
    }, 
    Mythic_Olipop = {
        index = 8, 
        sheet = 1
    }, 
    Rare_Olipop = {
        index = 9, 
        sheet = 1
    }, 
    Secret_Olipop = {
        index = 10, 
        sheet = 1
    }
};