return {
    _sheets = {
        [1] = "rbxassetid://114604222310428"
    }, 
    FlickeringLightbulbs = {
        index = 1, 
        sheet = 1
    }, 
    EncryptedVaultBlueprints = {
        index = 2, 
        sheet = 1
    }, 
    HackedSecurityCards = {
        index = 3, 
        sheet = 1
    }, 
    MutatedAcorns = {
        index = 4, 
        sheet = 1
    }, 
    VenomSac = {
        index = 5, 
        sheet = 1
    }, 
    EctoplasmicRopes = {
        index = 6, 
        sheet = 1
    }, 
    EVILTransmissionNodes = {
        index = 7, 
        sheet = 1
    }, 
    PossessedScrews = {
        index = 8, 
        sheet = 1
    }, 
    InfectedMicrophones = {
        index = 9, 
        sheet = 1
    }, 
    MalfunctioningLabEquipment = {
        index = 10, 
        sheet = 1
    }, 
    MalfunctioningSteeringWheel = {
        index = 11, 
        sheet = 1
    }, 
    AmpBuzzCoil = {
        index = 12, 
        sheet = 1
    }, 
    AncientPirateBlueprints = {
        index = 13, 
        sheet = 1
    }, 
    ArchivedChumBlueprints = {
        index = 14, 
        sheet = 1
    }, 
    BrokenHeroRelics = {
        index = 15, 
        sheet = 1
    }, 
    BuzzingAntennas = {
        index = 16, 
        sheet = 1
    }, 
    CitadelAccessCrystals = {
        index = 17, 
        sheet = 1
    }, 
    CorruptedCondimentPackets = {
        index = 18, 
        sheet = 1
    }, 
    CorruptedMusicNotes = {
        index = 19, 
        sheet = 1
    }, 
    DamagedAICores = {
        index = 20, 
        sheet = 1
    }, 
    OverloadedBassCoils = {
        index = 21, 
        sheet = 1
    }, 
    SmokedSignalFlare = {
        index = 22, 
        sheet = 1
    }, 
    FakeLicense = {
        index = 23, 
        sheet = 1
    }, 
    FracturedDomePanels = {
        index = 24, 
        sheet = 1
    }, 
    GlitchedSignposts = {
        index = 25, 
        sheet = 1
    }, 
    HijackedElevatorChips = {
        index = 26, 
        sheet = 1
    }, 
    PowerCores = {
        index = 27, 
        sheet = 1
    }, 
    JellyCoreFragments = {
        index = 28, 
        sheet = 1
    }, 
    SuspiciousOrderSlips = {
        index = 29, 
        sheet = 1
    }, 
    TaintedChumSamples = {
        index = 30, 
        sheet = 1
    }, 
    LivingGreaseBlobs = {
        index = 31, 
        sheet = 1
    }, 
    BarnacleManJournals = {
        index = 32, 
        sheet = 1
    }, 
    CrackedCymbals = {
        index = 33, 
        sheet = 1
    }, 
    PossessedMusicSheet = {
        index = 34, 
        sheet = 1
    }, 
    StolenRobotControlChips = {
        index = 35, 
        sheet = 1
    }, 
    VaultControlPanel = {
        index = 36, 
        sheet = 1
    }
};