return {
    [1] = {
        type = "Currency", 
        name = "Gems", 
        amount = 50
    }, 
    [2] = {
        type = "Currency", 
        name = "Coins", 
        amount = 100
    }, 
    [3] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [4] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 6
    }, 
    [5] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 2
    }, 
    [6] = {
        type = "Currency", 
        name = "Gems", 
        amount = 100
    }, 
    [7] = {
        type = "Currency", 
        name = "Coins", 
        amount = 200
    }, 
    [8] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [9] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 10
    }, 
    [10] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [11] = {
        type = "Currency", 
        name = "Gems", 
        amount = 200
    }, 
    [12] = {
        type = "Currency", 
        name = "Coins", 
        amount = 300
    }, 
    [13] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [14] = {
        type = "Inventory", 
        name = "Kelp Shake", 
        amount = 6
    }, 
    [15] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 4
    }, 
    [16] = {
        type = "Currency", 
        name = "Gems", 
        amount = 300
    }, 
    [17] = {
        type = "Currency", 
        name = "Coins", 
        amount = 400
    }, 
    [18] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [19] = {
        type = "Inventory", 
        name = "Kelp Shake", 
        amount = 10
    }, 
    [20] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [21] = {
        type = "Currency", 
        name = "Gems", 
        amount = 400
    }, 
    [22] = {
        type = "Currency", 
        name = "Coins", 
        amount = 500
    }, 
    [23] = {
        type = "Inventory", 
        name = "COINS_60", 
        amount = 1
    }, 
    [24] = {
        type = "Inventory", 
        name = "Krabby Patty", 
        amount = 6
    }, 
    [25] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 6
    }, 
    [26] = {
        type = "Currency", 
        name = "Gems", 
        amount = 500
    }, 
    [27] = {
        type = "Currency", 
        name = "Coins", 
        amount = 600
    }, 
    [28] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [29] = {
        type = "Inventory", 
        name = "Krabby Patty", 
        amount = 10
    }, 
    [30] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [31] = {
        type = "Currency", 
        name = "Gems", 
        amount = 600
    }, 
    [32] = {
        type = "Currency", 
        name = "Coins", 
        amount = 700
    }, 
    [33] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [34] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 16
    }, 
    [35] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 10
    }, 
    [36] = {
        type = "Currency", 
        name = "Gems", 
        amount = 700
    }, 
    [37] = {
        type = "Currency", 
        name = "Coins", 
        amount = 800
    }, 
    [38] = {
        type = "Inventory", 
        name = "COINS_60", 
        amount = 1
    }, 
    [39] = {
        type = "Inventory", 
        name = "Kelp Shake", 
        amount = 16
    }, 
    [40] = {
        type = "Currency", 
        name = "MagicConch", 
        amount = 1
    }, 
    [41] = {
        type = "Currency", 
        name = "Gems", 
        amount = 800
    }, 
    [42] = {
        type = "Currency", 
        name = "Coins", 
        amount = 900
    }, 
    [43] = {
        type = "Inventory", 
        name = "XP_60", 
        amount = 1
    }, 
    [44] = {
        type = "Inventory", 
        name = "Krabby Patty", 
        amount = 16
    }, 
    [45] = {
        type = "Currency", 
        name = "TraitRolls", 
        amount = 10
    }, 
    [46] = {
        type = "Currency", 
        name = "Gems", 
        amount = 1000
    }, 
    [47] = {
        type = "Currency", 
        name = "Coins", 
        amount = 1500
    }, 
    [48] = {
        type = "Inventory", 
        name = "GEMS_60", 
        amount = 1
    }, 
    [49] = {
        type = "Inventory", 
        name = "Chocolate Bar", 
        amount = 24
    }, 
    [50] = {
        type = "Unit", 
        name = "CavemanSpongebob", 
        amount = 1
    }
};