return {
    {
        displayName = "{amount} Trait Rerolls", 
        type = "Currency", 
        name = "TraitRolls", 
        amount = 10, 
        cost = {
            currency = "PrestigeToken", 
            amount = 1
        }
    }, 
    {
        displayName = "{amount} Magic Conches", 
        type = "Currency", 
        name = "MagicConch", 
        amount = 10, 
        cost = {
            currency = "PrestigeToken", 
            amount = 2
        }
    }, 
    {
        displayName = "{amount} Epic Chests", 
        type = "Inventory", 
        name = "EpicTreasureChest", 
        amount = 25, 
        cost = {
            currency = "PrestigeToken", 
            amount = 3
        }
    }, 
    {
        displayName = "{amount} Legendary Chests", 
        type = "Inventory", 
        name = "LegendaryTreasureChest", 
        amount = 25, 
        cost = {
            currency = "PrestigeToken", 
            amount = 5
        }
    }, 
    {
        displayName = "{amount} Mythic Chests", 
        type = "Inventory", 
        name = "MythicTreasureChest", 
        amount = 25, 
        cost = {
            currency = "PrestigeToken", 
            amount = 8
        }
    }, 
    {
        displayName = "Random Legendary Unit", 
        type = "RandomUnit", 
        rarity = "Legendary", 
        extraData = {
            Shiny = true, 
            Wumbo = true
        }, 
        poolName = "Standard", 
        amount = 1, 
        cost = {
            currency = "PrestigeToken", 
            amount = 15
        }
    }, 
    {
        displayName = "Random Mythic Unit", 
        type = "RandomUnit", 
        rarity = "Mythic", 
        extraData = {
            Shiny = true, 
            Wumbo = true
        }, 
        poolName = "Standard", 
        amount = 1, 
        cost = {
            currency = "PrestigeToken", 
            amount = 50
        }
    }, 
    {
        displayName = "Secret Unit ???", 
        type = "Unit", 
        name = "Spongehenge", 
        extraData = {
            Shiny = true, 
            Wumbo = true
        }, 
        amount = 1, 
        secret = true, 
        cost = {
            currency = "PrestigeToken", 
            amount = 100
        }
    }, 
    {
        displayName = "Secret Unit ???", 
        type = "Unit", 
        name = "Spongehenge", 
        extraData = {
            Shiny = true, 
            Wumbo = true, 
            Stars = 5
        }, 
        amount = 1, 
        secret = true, 
        cost = {
            currency = "PrestigeToken", 
            amount = 250
        }
    }
};