return {
    PityEnabled = true, 
    RaritiesPool = {
        Secret = {
            weight = 100
        }
    }, 
    LootPool = {
        Secret = {
            {
                type = "Inventory", 
                name = "BubblePatty", 
                amount = 1, 
                weight = 52.5
            }, 
            {
                type = "Inventory", 
                name = "SecretTreasureChest", 
                amount = 1, 
                weight = 26
            }, 
            {
                type = "Inventory", 
                name = "HydroHowler", 
                amount = 1, 
                weight = 15.25
            }, 
            {
                type = "Inventory", 
                name = "BubbleBoat", 
                amount = 1, 
                weight = 5
            }, 
            {
                type = "Unit", 
                name = "BubblePoppinBoys", 
                amount = 1, 
                weight = 1, 
                pityAmount = 124
            }, 
            {
                type = "Unit", 
                name = "BubblePoppinBoys", 
                extraData = {
                    Shiny = true, 
                    Wumbo = true
                }, 
                amount = 1, 
                weight = 0.25, 
                pityAmount = 250
            }
        }
    }
};