return {
    {
        type = "Inventory", 
        name = "COINS_60", 
        rarity = "Legendary", 
        amount = 1, 
        weight = 25
    }, 
    {
        type = "Inventory", 
        name = "GEMS_60", 
        rarity = "Legendary", 
        amount = 1, 
        weight = 25
    }, 
    {
        type = "Inventory", 
        name = "XP_60", 
        rarity = "Legendary", 
        amount = 1, 
        weight = 25
    }
};