return {
    AnchorArms_1 = {
        damage = 5
    }, 
    AnchorArms_2 = {
        damage = 10
    }, 
    AnchorArms_3 = {
        damage = 15
    }, 
    TurboTartar_1 = {
        cooldown = 5
    }, 
    TurboTartar_2 = {
        cooldown = 10
    }, 
    TurboTartar_3 = {
        cooldown = 15
    }, 
    ScopeShell_1 = {
        range = 5
    }, 
    ScopeShell_2 = {
        range = 10
    }, 
    ScopeShell_3 = {
        range = 15
    }, 
    PowerPatty = {
        damage = 25, 
        cooldown = 25, 
        range = 25
    }, 
    LifeguardWhistle = {
        damage = 15, 
        cooldown = 10, 
        range = 20
    }
};