return {
    VariantsPool = {
        Normal = {
            weight = 98
        }, 
        Shiny = {
            weight = 1
        }, 
        Wumbo = {
            weight = 0.67
        }, 
        ShinyWumbo = {
            weight = 0.33
        }
    }, 
    RaritiesPool = {
        Rare = {
            weight = 55
        }, 
        Epic = {
            weight = 35
        }, 
        Legendary = {
            weight = 7
        }, 
        Mythic = {
            weight = 2.95
        }, 
        Secret = {
            weight = 0.05
        }
    }, 
    LootPool = {
        Rare = {
            {
                type = "Unit", 
                name = "Anchovy", 
                extraData = {}, 
                amount = 1, 
                weight = 27.5
            }, 
            {
                type = "Unit", 
                name = "Fishstick", 
                extraData = {}, 
                amount = 1, 
                weight = 27.5
            }
        }, 
        Epic = {
            {
                type = "Unit", 
                name = "Harold", 
                extraData = {}, 
                amount = 1, 
                weight = 17.5
            }, 
            {
                type = "Unit", 
                name = "MrMailman", 
                extraData = {}, 
                amount = 1, 
                weight = 17.5
            }
        }, 
        Legendary = {
            {
                type = "Unit", 
                name = "OldManWalker", 
                extraData = {}, 
                amount = 1, 
                weight = 7
            }
        }, 
        Mythic = {
            {
                type = "Unit", 
                name = "BusStation", 
                extraData = {}, 
                amount = 1, 
                weight = 2.95
            }
        }, 
        Secret = {
            {
                type = "Unit", 
                name = "BikiniBottomPD", 
                extraData = {}, 
                amount = 1, 
                weight = 0.025
            }, 
            {
                type = "Unit", 
                name = "TheAppetizer", 
                extraData = {}, 
                amount = 1, 
                weight = 0.025
            }
        }
    }
};