return {
    VariantsPool = {
        Normal = {
            weight = 95
        }, 
        Shiny = {
            weight = 3
        }, 
        Wumbo = {
            weight = 1.5
        }, 
        ShinyWumbo = {
            weight = 0.5
        }
    }, 
    RaritiesPool = {
        Epic = {
            weight = 56
        }, 
        Legendary = {
            weight = 40
        }, 
        Mythic = {
            weight = 3.75
        }, 
        Secret = {
            weight = 0.25
        }
    }, 
    BoostedRaritiesPool = {
        Epic = {
            weight = 42
        }, 
        Legendary = {
            weight = 50
        }, 
        Mythic = {
            weight = 7.5
        }, 
        Secret = {
            weight = 0.5
        }
    }, 
    LootPool = {
        Epic = {
            {
                type = "Unit", 
                name = "RippedPantsBob", 
                extraData = {}, 
                amount = 1, 
                weight = 56
            }
        }, 
        Legendary = {
            {
                type = "Unit", 
                name = "MusclebobBuffpants", 
                extraData = {}, 
                amount = 1, 
                weight = 40
            }
        }, 
        Mythic = {
            {
                type = "Unit", 
                name = "CraigMammalton", 
                extraData = {}, 
                amount = 1, 
                weight = 1.875
            }, 
            {
                type = "Unit", 
                name = "JackKahunaLaguna", 
                extraData = {}, 
                amount = 1, 
                weight = 1.875
            }
        }, 
        Secret = {
            {
                type = "Unit", 
                name = "RedbeardKrabs", 
                extraData = {}, 
                amount = 1, 
                weight = 0.25
            }
        }
    }
};