return {
    ShopOrder = 1, 
    Cost = {
        currencyName = "Gems", 
        price = 100
    }, 
    Pool = {
        RaritiesPool = {
            Common = {
                weight = 49.51, 
                shinyWeight = 3.5, 
                megaWeight = 1.75, 
                megaShinyWeight = 0.75
            }, 
            Uncommon = {
                weight = 27.88, 
                shinyWeight = 3.25, 
                megaWeight = 1.65, 
                megaShinyWeight = 0.6
            }, 
            Rare = {
                weight = 17.48, 
                shinyWeight = 2.25, 
                megaWeight = 1.25, 
                megaShinyWeight = 0.5
            }, 
            Epic = {
                weight = 3.4, 
                shinyWeight = 1, 
                megaWeight = 0.5, 
                megaShinyWeight = 0.25
            }, 
            Legendary = {
                weight = 1.15, 
                shinyWeight = 0.1, 
                megaWeight = 0.075, 
                megaShinyWeight = 0.025
            }, 
            Mythic = {
                weight = 0.55, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }, 
            Secret = {
                weight = 0.025, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }, 
            Exotic = {
                weight = 0.005, 
                shinyWeight = 0.025, 
                megaWeight = 0.0025, 
                megaShinyWeight = 0.00175
            }
        }, 
        UnitsPool = {
            Common = {
                {
                    type = "Unit", 
                    name = "Spongebob", 
                    weight = 9.906
                }, 
                {
                    type = "Unit", 
                    name = "Patrick", 
                    weight = 9.906
                }, 
                {
                    type = "Unit", 
                    name = "Squidward", 
                    weight = 9.906
                }, 
                {
                    type = "Unit", 
                    name = "Gary", 
                    weight = 9.906
                }, 
                {
                    type = "Unit", 
                    name = "Sandy", 
                    weight = 9.906
                }
            }, 
            Uncommon = {
                {
                    type = "Unit", 
                    name = "BarnacleBoy", 
                    weight = 3.975
                }, 
                {
                    type = "Unit", 
                    name = "Jim", 
                    weight = 3.975
                }, 
                {
                    type = "Unit", 
                    name = "BubbleBass", 
                    weight = 3.975
                }, 
                {
                    type = "Unit", 
                    name = "Gene", 
                    weight = 3.975
                }, 
                {
                    type = "Unit", 
                    name = "GoofyGooberWaiter", 
                    weight = 3.975
                }, 
                {
                    type = "Unit", 
                    name = "BarnacleBoyPatrick", 
                    weight = 4
                }, 
                {
                    type = "Unit", 
                    name = "KarateSpongebob", 
                    weight = 4
                }
            }, 
            Rare = {
                {
                    type = "Unit", 
                    name = "GrandmaSquarePants", 
                    weight = 2
                }, 
                {
                    type = "Unit", 
                    name = "OldManJenkins", 
                    weight = 2
                }, 
                {
                    type = "Unit", 
                    name = "Pearl", 
                    weight = 2
                }, 
                {
                    type = "Unit", 
                    name = "KevinCCucumber", 
                    weight = 2.225
                }, 
                {
                    type = "Unit", 
                    name = "MrsPuff", 
                    weight = 2.75
                }, 
                {
                    type = "Unit", 
                    name = "LordRoyalHighness", 
                    weight = 2
                }, 
                {
                    type = "Unit", 
                    name = "KrustyKrab", 
                    weight = 1.5
                }, 
                {
                    type = "Unit", 
                    name = "ElasticWaistband", 
                    weight = 1.5
                }, 
                {
                    type = "Unit", 
                    name = "KarateSandy", 
                    weight = 1.5
                }
            }, 
            Epic = {
                {
                    type = "Unit", 
                    name = "LarryTheLobster", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "Karen", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "PrincessMindy", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "DirtyBubble", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "MermaidManSpongebob", 
                    weight = 0.6
                }, 
                {
                    type = "Unit", 
                    name = "SandCreature", 
                    weight = 0.4
                }
            }, 
            Legendary = {
                {
                    type = "Unit", 
                    name = "MrKrabs", 
                    weight = 0.25
                }, 
                {
                    type = "Unit", 
                    name = "Plankton", 
                    weight = 0.25
                }, 
                {
                    type = "Unit", 
                    name = "Doodlebob", 
                    weight = 0.25
                }, 
                {
                    type = "Unit", 
                    name = "MissAppear", 
                    weight = 0.25
                }, 
                {
                    type = "Unit", 
                    name = "Jojo", 
                    weight = 0.15
                }
            }, 
            Mythic = {
                {
                    type = "Unit", 
                    name = "SmittyWerbenjagermanjensen", 
                    weight = 0.071
                }, 
                {
                    type = "Unit", 
                    name = "RealisticFishHead", 
                    weight = 0.071
                }, 
                {
                    type = "Unit", 
                    name = "KingNeptune", 
                    weight = 0.084
                }, 
                {
                    type = "Unit", 
                    name = "ManRay", 
                    weight = 0.091
                }, 
                {
                    type = "Unit", 
                    name = "MermaidMan", 
                    weight = 0.081
                }, 
                {
                    type = "Unit", 
                    name = "DirtyDan", 
                    weight = 0.051
                }, 
                {
                    type = "Unit", 
                    name = "PinheadLarry", 
                    weight = 0.051
                }, 
                {
                    type = "Unit", 
                    name = "Tiff", 
                    weight = 0.025
                }, 
                {
                    type = "Unit", 
                    name = "Bert", 
                    weight = 0.02
                }
            }, 
            Secret = {
                {
                    type = "Unit", 
                    name = "CyborgPlankton", 
                    weight = 0.014, 
                    secretUnit = true
                }, 
                {
                    type = "Unit", 
                    name = "SeaBear", 
                    weight = 0.007, 
                    secretUnit = true
                }, 
                {
                    type = "Unit", 
                    name = "Plank-Ton", 
                    weight = 0.004, 
                    secretUnit = true
                }
            }, 
            Exotic = {
                {
                    type = "Unit", 
                    name = "PatTheHapless", 
                    weight = 0.0025
                }, 
                {
                    type = "Unit", 
                    name = "CannonballJenkins", 
                    weight = 0.0025
                }
            }
        }
    }
};