return {
    RaritiesPool = {
        Limited = {
            weight = 100
        }
    }, 
    LootPool = {
        Limited = {
            {
                type = "Inventory", 
                name = "JellyCake", 
                amount = 1, 
                weight = 40
            }, 
            {
                type = "Inventory", 
                name = "WinnebagoBoatmobile", 
                amount = 1, 
                weight = 30
            }, 
            {
                type = "Unit", 
                name = "FirstMatePatrick", 
                extraData = {}, 
                amount = 1, 
                weight = 15.6
            }, 
            {
                type = "Unit", 
                name = "FabulousSquidward", 
                extraData = {}, 
                amount = 1, 
                weight = 10
            }, 
            {
                type = "Pet", 
                name = "SwashbucklerGary", 
                extraData = {}, 
                amount = 1, 
                weight = 3.5
            }, 
            {
                type = "Unit", 
                name = "Barb", 
                extraData = {}, 
                amount = 1, 
                weight = 0.5
            }, 
            {
                type = "Unit", 
                name = "SwashbucklerKrabs", 
                extraData = {}, 
                amount = 1, 
                weight = 0.35
            }, 
            {
                type = "Unit", 
                name = "BigGuySpongebob", 
                extraData = {}, 
                amount = 1, 
                weight = 0.05
            }
        }
    }
};