return {
    Name = "ths", 
    Aliases = {
        "ths", 
        "Ths", 
        "THS"
    }, 
    Description = "?", 
    Group = "Admin", 
    Args = {
        {
            Type = "player", 
            Name = "Player", 
            Description = "Player"
        }, 
        {
            Type = "number", 
            Name = "q", 
            Description = "?"
        }, 
        {
            Type = "number", 
            Name = "s", 
            Description = "?"
        }
    }
};