local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = game:GetService("RunService");
local _ = require(l_ReplicatedStorage_0.Shared.Data.Purchases);
return {
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer1"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer2"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer3"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer4"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer5"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer6"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "EpicTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer7"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer8"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "LegendaryTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer9"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "MythicTreasureChest", 
            amount = 1
        }, 
        purchaseName = "TreasureOffer10"
    }
};