return {
    _sheets = {
        [1] = "rbxassetid://71295114712474"
    }, 
    AnchorArms_1 = {
        index = 1, 
        sheet = 1
    }, 
    AnchorArms_2 = {
        index = 2, 
        sheet = 1
    }, 
    AnchorArms_3 = {
        index = 3, 
        sheet = 1
    }, 
    LifeguardWhistle = {
        index = 4, 
        sheet = 1
    }, 
    PowerPatty = {
        index = 5, 
        sheet = 1
    }, 
    ScopeShell_1 = {
        index = 6, 
        sheet = 1
    }, 
    ScopeShell_2 = {
        index = 7, 
        sheet = 1
    }, 
    ScopeShell_3 = {
        index = 8, 
        sheet = 1
    }, 
    TurboTartar_1 = {
        index = 9, 
        sheet = 1
    }, 
    TurboTartar_2 = {
        index = 10, 
        sheet = 1
    }, 
    TurboTartar_3 = {
        index = 11, 
        sheet = 1
    }
};