return {
    GrannyTentacles = {
        index = 1, 
        sheet = 3
    }, 
    SwashbucklerKrabs = {
        index = 2, 
        sheet = 3
    }, 
    BandMrKrabs = {
        index = 3, 
        sheet = 3
    }, 
    Tattletale = {
        index = 4, 
        sheet = 3
    }, 
    TexasSandy = {
        index = 5, 
        sheet = 3
    }, 
    BandSandy = {
        index = 6, 
        sheet = 3
    }, 
    TheAppetizer = {
        index = 7, 
        sheet = 3
    }, 
    TheRodent = {
        index = 8, 
        sheet = 3
    }, 
    TheTickler = {
        index = 9, 
        sheet = 3
    }, 
    TheMoth = {
        index = 10, 
        sheet = 3
    }, 
    TheSquarePants = {
        index = 11, 
        sheet = 3
    }, 
    ToyBob = {
        index = 12, 
        sheet = 3
    }, 
    AlaskanBullWorm = {
        index = 13, 
        sheet = 3
    }, 
    Anchovy = {
        index = 14, 
        sheet = 3
    }, 
    ArmyOfTheLivingDead = {
        index = 15, 
        sheet = 3
    }, 
    AtomicFlounder = {
        index = 16, 
        sheet = 3
    }, 
    BabyPrunes = {
        index = 17, 
        sheet = 3
    }, 
    BandMrsPuff = {
        index = 18, 
        sheet = 3
    }, 
    Barb = {
        index = 19, 
        sheet = 3
    }, 
    BargNMart = {
        index = 20, 
        sheet = 3
    }, 
    BarnacleMan = {
        index = 21, 
        sheet = 3
    }, 
    BemmyBuddy = {
        index = 22, 
        sheet = 3
    }, 
    Bert = {
        index = 23, 
        sheet = 3
    }, 
    Fishstick = {
        index = 24, 
        sheet = 3
    }, 
    BigGuySpongebob = {
        index = 25, 
        sheet = 3
    }, 
    BikiniBottomPD = {
        index = 26, 
        sheet = 3
    }, 
    BreakfastMonster = {
        index = 27, 
        sheet = 3
    }, 
    BrokenSquidward = {
        index = 28, 
        sheet = 3
    }, 
    BubbleBuddy = {
        index = 29, 
        sheet = 3
    }, 
    BubblePoppinBoys = {
        index = 30, 
        sheet = 3
    }, 
    Bubbles = {
        index = 31, 
        sheet = 3
    }, 
    BuffSandy = {
        index = 32, 
        sheet = 3
    }, 
    BunkerBoys = {
        index = 33, 
        sheet = 3
    }, 
    BusStation = {
        index = 34, 
        sheet = 3
    }, 
    CannonballJenkins = {
        index = 35, 
        sheet = 3
    }, 
    CaptainMagma = {
        index = 36, 
        sheet = 3
    }, 
    CaptainZach = {
        index = 37, 
        sheet = 3
    }, 
    HashSlingingSlasher = {
        index = 38, 
        sheet = 3
    }, 
    CavemanSpongebob = {
        index = 39, 
        sheet = 3
    }, 
    ChumBrute = {
        index = 40, 
        sheet = 3
    }, 
    Clamu = {
        index = 41, 
        sheet = 3
    }, 
    CommandModule = {
        index = 42, 
        sheet = 3
    }, 
    CraigMammalton = {
        index = 43, 
        sheet = 3
    }, 
    CuddleEHugs = {
        index = 44, 
        sheet = 3
    }, 
    DarkKnight = {
        index = 45, 
        sheet = 3
    }, 
    Dennis = {
        index = 46, 
        sheet = 3
    }, 
    DirtyBubble = {
        index = 47, 
        sheet = 3
    }, 
    DirtyDan = {
        index = 48, 
        sheet = 3
    }, 
    Doodlebob = {
        index = 49, 
        sheet = 3
    }, 
    Dorudon = {
        index = 50, 
        sheet = 3
    }, 
    DreamGary = {
        index = 51, 
        sheet = 3
    }, 
    DreamPatrick = {
        index = 52, 
        sheet = 3
    }, 
    DrGillGilliam = {
        index = 53, 
        sheet = 3
    }, 
    DuelSpongebob = {
        index = 54, 
        sheet = 3
    }, 
    DungeonMaster = {
        index = 55, 
        sheet = 3
    }, 
    EasterBunnySpongebob = {
        index = 56, 
        sheet = 3
    }, 
    ElasticWaistband = {
        index = 57, 
        sheet = 3
    }, 
    FabulousSquidward = {
        index = 58, 
        sheet = 3
    }, 
    FilthyPhil = {
        index = 59, 
        sheet = 3
    }, 
    FilthyBoys = {
        index = 60, 
        sheet = 3
    }, 
    FishnetPatrick = {
        index = 61, 
        sheet = 3
    }, 
    Gary = {
        index = 62, 
        sheet = 3
    }, 
    Gene = {
        index = 63, 
        sheet = 3
    }, 
    GGRockSpongebob = {
        index = 64, 
        sheet = 3
    }
};