return {
    MegaHydraKaren = {
        index = 1, 
        sheet = 2
    }, 
    MermaidManSpongebob = {
        index = 2, 
        sheet = 2
    }, 
    MermaidMan = {
        index = 3, 
        sheet = 2
    }, 
    MerryGary = {
        index = 4, 
        sheet = 2
    }, 
    MimicBob = {
        index = 5, 
        sheet = 2
    }, 
    MorbidSpongebob = {
        index = 6, 
        sheet = 2
    }, 
    MrMailman = {
        index = 7, 
        sheet = 2
    }, 
    MrsPuff = {
        index = 8, 
        sheet = 2
    }, 
    MrSuperAwesomeness = {
        index = 9, 
        sheet = 2
    }, 
    Patar = {
        index = 10, 
        sheet = 2
    }, 
    PinheadLarry = {
        index = 11, 
        sheet = 2
    }, 
    BuffPatrick = {
        index = 12, 
        sheet = 2
    }, 
    GladiatorPatrick = {
        index = 13, 
        sheet = 2
    }, 
    MusclebobBuffpants = {
        index = 14, 
        sheet = 2
    }, 
    Nat = {
        index = 15, 
        sheet = 2
    }, 
    Nocturna = {
        index = 16, 
        sheet = 2
    }, 
    Nosferatu = {
        index = 17, 
        sheet = 2
    }, 
    Cyclops = {
        index = 18, 
        sheet = 2
    }, 
    OldManWalker = {
        index = 19, 
        sheet = 2
    }, 
    OlympianSpongebob = {
        index = 20, 
        sheet = 2
    }, 
    PaintyThePirate = {
        index = 21, 
        sheet = 2
    }, 
    Patricia = {
        index = 22, 
        sheet = 2
    }, 
    PatrickSandRobot = {
        index = 23, 
        sheet = 2
    }, 
    PatTheHapless = {
        index = 24, 
        sheet = 2
    }, 
    PattyObsessedSquidward = {
        index = 25, 
        sheet = 2
    }, 
    Pearl = {
        index = 26, 
        sheet = 2
    }, 
    PerchPerkins = {
        index = 27, 
        sheet = 2
    }, 
    ["Plank-Ton"] = {
        index = 28, 
        sheet = 2
    }, 
    PrehistoricGary = {
        index = 29, 
        sheet = 2
    }, 
    PrehistoricKrabs = {
        index = 30, 
        sheet = 2
    }, 
    PrincessMindy = {
        index = 31, 
        sheet = 2
    }, 
    PrincessPearl = {
        index = 32, 
        sheet = 2
    }, 
    BandPearl = {
        index = 33, 
        sheet = 2
    }, 
    Quickster = {
        index = 34, 
        sheet = 2
    }, 
    RedbeardKrabs = {
        index = 35, 
        sheet = 2
    }, 
    Richard = {
        index = 36, 
        sheet = 2
    }, 
    RippedPantsBob = {
        index = 37, 
        sheet = 2
    }, 
    RobotMantis = {
        index = 38, 
        sheet = 2
    }, 
    Rrarrg = {
        index = 39, 
        sheet = 2
    }, 
    RustyRickets = {
        index = 40, 
        sheet = 2
    }, 
    SandCreature = {
        index = 41, 
        sheet = 2
    }, 
    Sandy = {
        index = 42, 
        sheet = 2
    }, 
    SantaClaus = {
        index = 43, 
        sheet = 2
    }, 
    SeaBear = {
        index = 44, 
        sheet = 2
    }, 
    SeaRhino = {
        index = 45, 
        sheet = 2
    }, 
    SirPatrick = {
        index = 46, 
        sheet = 2
    }, 
    BandPatrick = {
        index = 47, 
        sheet = 2
    }, 
    BarnacleBoyPatrick = {
        index = 48, 
        sheet = 2
    }, 
    FirstMatePatrick = {
        index = 49, 
        sheet = 2
    }, 
    SirSpongebob = {
        index = 50, 
        sheet = 2
    }, 
    BandSpongebob = {
        index = 51, 
        sheet = 2
    }, 
    SlappyLaszlo = {
        index = 52, 
        sheet = 2
    }, 
    SmittyWerbenjagermanjensen = {
        index = 53, 
        sheet = 2
    }, 
    SnowMollusk = {
        index = 54, 
        sheet = 2
    }, 
    SnowSponge = {
        index = 55, 
        sheet = 2
    }, 
    Spongebob = {
        index = 56, 
        sheet = 2
    }, 
    SpongebobSanta = {
        index = 57, 
        sheet = 2
    }, 
    SpongeGar = {
        index = 58, 
        sheet = 2
    }, 
    Spongehenge = {
        index = 59, 
        sheet = 2
    }, 
    Spot = {
        index = 60, 
        sheet = 2
    }, 
    SquidasaurusRex = {
        index = 61, 
        sheet = 2
    }, 
    SquidlyTentacles = {
        index = 62, 
        sheet = 2
    }, 
    SquidwardSanta = {
        index = 63, 
        sheet = 2
    }, 
    Squog = {
        index = 64, 
        sheet = 2
    }
};