local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = game:GetService("RunService");
local _ = require(l_ReplicatedStorage_0.Shared.Data.Purchases);
return {
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 50
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "Aged Patty", 
            amount = 2
        }, 
        isFree = false, 
        purchaseName = "UnlimitedOffer1"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Coins", 
            amount = 500
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "XP_60", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Currency", 
            name = "MagicConch", 
            amount = 1
        }, 
        isFree = false, 
        purchaseName = "UnlimitedOffer2"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Gems", 
            amount = 250
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Coins", 
            amount = 2500
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Currency", 
            name = "TraitRolls", 
            amount = 2
        }, 
        isFree = false, 
        purchaseName = "UnlimitedOffer3"
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "Pretty Patties", 
            amount = 2
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Inventory", 
            name = "GEMS_60", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Currency", 
            name = "Coins", 
            amount = 7500
        }, 
        isFree = false, 
        purchaseName = "UnlimitedOffer4"
    }, 
    {
        reward = {
            type = "Currency", 
            name = "MagicConch", 
            amount = 1
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Currency", 
            name = "TraitRolls", 
            amount = 2
        }, 
        isFree = true
    }, 
    {
        reward = {
            type = "Unit", 
            name = "BabyPrunes", 
            amount = 1
        }, 
        isFree = false, 
        purchaseName = "UnlimitedOffer5"
    }
};