return {
    package = {
        authors = {
            "PenguinDevs", 
            "Xan_TheDragon"
        }, 
        description = "A fork of PartCache by Xan_TheDragon https://devforum.roblox.com/t/partcache-for-all-your-quick-part-creation-needs/246641. InstanceCache is not limited to only BaseParts, but works with any instances too.", 
        license = "MIT", 
        name = "penguindevs/instance-cache", 
        realm = "shared", 
        registry = "https://github.com/UpliftGames/wally-index", 
        version = "1.0.4"
    }
};