return {
    dependencies = {
        Fusion_v0_2_0 = "elttob/fusion@0.2.0", 
        Fusion_v0_3_0 = "elttob/fusion@0.3.0", 
        Janitor = "howmanysmall/janitor@^1.16.0", 
        Promise = "evaera/promise@^4.0.0", 
        Signal = "sleitnick/signal@2", 
        T = "osyrisrblx/t@3.1.1", 
        Trove = "sleitnick/trove@1"
    }, 
    package = {
        authors = {
            "Logan Hunt (Raildex)"
        }, 
        description = "A collection of utility functions for Roblox Luau.", 
        license = "MIT", 
        name = "raild3x/railutil", 
        realm = "shared", 
        registry = "https://github.com/UpliftGames/wally-index", 
        version = "1.15.0"
    }
};