return {
    dependencies = {
        Promise = "evaera/promise@4.0.0", 
        Signal = "sleitnick/signal@1.5.0"
    }, 
    package = {
        description = "BezierTweens allows for Tweens using Bezier Curves", 
        license = "MIT", 
        name = "max-bacon/bezier-tweens", 
        realm = "shared", 
        registry = "https://github.com/UpliftGames/wally-index", 
        version = "1.2.1"
    }
};